/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class deudaHistoria extends javax.swing.JInternalFrame {

      private  String[]  titulos = {"Id","Fecha","Total","No. Compra","id Proveedor","Total Pagos","Total pagado"},
              titulosMat = {"Id","Nombre","Alto","Ancho","Cantidad","Color","Tipo","Costo","Cantidad Comprada"},
              tituloCredito = {"Id","Pago","Fecha"};
     private String localhost = "localhost",puerto = "3305",baseDeDatos = "proyectobd3",usuario ="root",contra = "xela2020";
     private ButtonGroup grupoDeRadio;
     private ConexionMySQL conexion;
     public deudaHistoria() {
        initComponents();
        conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
        grupoDeRadio = new ButtonGroup();
        grupoDeRadio.add(radioDeuda);
        grupoDeRadio.add(radioSaldo);
        radioSaldo.setSelected(true);
      
        
        botonPagar.setEnabled(false);
        botonRegresar.setEnabled(false);
        
        txtFechaF.setEnabled(false);
        txtFechaI.setEnabled(false);
        botonCragarFecha.setEnabled(false);
        
       tabbedCompra.setEnabledAt(1,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        tabbedCompra = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompra = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        radioDeuda = new javax.swing.JRadioButton();
        radioSaldo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        botonCargarId = new javax.swing.JButton();
        comoboCargar = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFechaI = new javax.swing.JTextField();
        txtFechaF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonCragarFecha = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelNumCuenta = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelIdProveedor = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMat = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPago = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelSubTotal = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lableIdCompra = new javax.swing.JLabel();
        labelFechaC = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botonDetalle = new javax.swing.JButton();
        botonPagar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        jScrollPane4.setViewportView(jTextPane1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCompra);

        jLabel4.setText("Compras");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        radioDeuda.setText("Deudas");
        radioDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDeudaActionPerformed(evt);
            }
        });

        radioSaldo.setText("Saldados");
        radioSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSaldoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de compra");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(radioDeuda)
                .addGap(81, 81, 81)
                .addComponent(radioSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSaldo)
                    .addComponent(radioDeuda))
                .addGap(20, 20, 20))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonCargarId.setText("Cargar");
        botonCargarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarIdActionPerformed(evt);
            }
        });

        comoboCargar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Rango De Fecha" }));
        comoboCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoboCargarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID / No. COMPRA");

        jLabel2.setText("FECHA INICIO");

        jLabel3.setText("FECHA FINAL");

        jLabel5.setText("Forma de busqueda");

        botonCragarFecha.setText("Cargar");
        botonCragarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCragarFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addComponent(txtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(comoboCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonCragarFecha)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(botonCargarId)
                                                .addGap(34, 34, 34)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(235, 235, 235))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comoboCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCragarFecha)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        tabbedCompra.addTab("Compra", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Proveedor");

        jLabel10.setText("NOMBRE:");

        jLabel11.setText("TELEFONO:");

        jLabel12.setText("CELULAR:");

        jLabel13.setText("DIRECCION:");

        jLabel14.setText("CORREO:");

        jLabel15.setText("No. CUENTA:");

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombre.setText("nombre");

        labelTelefono.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTelefono.setText("telefono");

        labelDireccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelDireccion.setText("direccion");

        labelNumCuenta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNumCuenta.setText("num");

        labelCelular.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCelular.setText("Celular");

        labelCorreo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCorreo.setText("correo");

        jLabel20.setText("ID PROVEEDOR");

        labelIdProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelIdProveedor.setText("jLabel21");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel20))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(labelIdProveedor)
                    .addComponent(labelTelefono)
                    .addComponent(labelDireccion))
                .addGap(61, 61, 61)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel12))
                    .addComponent(jLabel15))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCelular)
                    .addComponent(labelCorreo)
                    .addComponent(labelNumCuenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(labelIdProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelTelefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelDireccion)
                    .addComponent(jLabel14)
                    .addComponent(labelCorreo))
                .addGap(26, 26, 26))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(labelNumCuenta)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(labelCelular))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaMat);

        jLabel8.setText("Materiales");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaPago);

        jLabel9.setText("Pagos");

        jLabel21.setText("TOTAL DE PAGOS ");

        labelSubTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelSubTotal.setText("jLabel22");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(26, 26, 26)
                .addComponent(labelSubTotal)
                .addGap(74, 74, 74))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(labelSubTotal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Compra");

        jLabel17.setText("ID COMPRA");

        jLabel18.setText("FECHA");

        jLabel19.setText("TOTAL");

        lableIdCompra.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lableIdCompra.setText("jLabel20");

        labelFechaC.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFechaC.setText("jLabel21");

        labelTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTotal.setText("jLabel22");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lableIdCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(labelFechaC)
                .addGap(85, 85, 85)
                .addComponent(jLabel19)
                .addGap(21, 21, 21)
                .addComponent(labelTotal)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(lableIdCompra)
                    .addComponent(labelFechaC)
                    .addComponent(labelTotal))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedCompra.addTab("Detalle", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonDetalle.setText("Detalle");
        botonDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetalleActionPerformed(evt);
            }
        });

        botonPagar.setText("Pagar");
        botonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarActionPerformed(evt);
            }
        });

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(botonDetalle)
                .addGap(44, 44, 44)
                .addComponent(botonPagar)
                .addGap(54, 54, 54)
                .addComponent(botonRegresar)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedCompra)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String fecha(){
    LocalDate fecha1 = LocalDate.now();
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    return fecha1.format(dtf);
    }
private void cargarTablaId(String consulta, String parametro, String cadena, String id, String extra,String entrada,JTable tabla, String[] titulo){
    String campo = parametro;
        String where = "";
        if(!"".equals(campo)){
            where = entrada+id+ "= "+campo+" or "+cadena+"= '"+campo+"'";
        }
         try {
         DefaultTableModel modelo = new DefaultTableModel(null,titulo);
         tabla.setModel(modelo);
         conexion.EjecutarConsulta(consulta+where+" "+extra);
            
            ResultSet rs = conexion.getResulSet();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
              
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i=0; i <cantidadColumnas ; i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,"Error de conexion","Error",JOptionPane.ERROR_MESSAGE);
         System.out.println(ex.getMessage());
        
    }
}
private void cargarTablaFecha(String consulta,JTable tabla, String[] titulo){
     try {
         DefaultTableModel modelo = new DefaultTableModel(null,titulo);
         tabla.setModel(modelo);
         conexion.EjecutarConsulta(consulta);
            
            ResultSet rs = conexion.getResulSet();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
              
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i=0; i <cantidadColumnas ; i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,"Error de conexion","Error",JOptionPane.ERROR_MESSAGE);
         System.out.println(ex.getMessage());
        
    }
    
}

private void datosProveedor(String idProveedor){
    
    conexion.EjecutarConsulta("select * from proveedor P  where id = "+idProveedor);
    ResultSet rs = conexion.getResulSet();
          try {
              
              ResultSetMetaData rsMd = rs.getMetaData();
              while(rs.next()){
                labelNombre.setText(rs.getString("nombre"));
                labelTelefono.setText(rs.getString("telefono"));
                labelCelular.setText(rs.getString("celular"));
                labelDireccion.setText(rs.getString("direccion"));
                labelCorreo.setText(rs.getString("correo"));
                labelNumCuenta.setText(rs.getString("num_cuenta"));
                labelIdProveedor.setText(rs.getString("id"));
                
                }
          } catch (SQLException ex) {
              Logger.getLogger(deudaHistoria.class.getName()).log(Level.SEVERE, null, ex);
          }
}
private void consultaTablaCredito(String idCompra){
   String  consulta = "select C.id,C.abono,C.fecha from credito_has_compra CC\n" +
"inner join credito C on CC.credito_id = C.id\n" +
"inner join compra Con on CC.compra_id = Con.id ";
       cargarTablaId(consulta,idCompra," Con.no_factura ", " Con.id ",""," where ", tablaPago, tituloCredito);
}
private float sumaPagas(String idCompra){
    float totalPago = 0;
    try {
            conexion.EjecutarConsulta("select sum(C.abono) as totalPagado from credito_has_compra CC\n" +
"inner join credito C on CC.credito_id = C.id\n" +
"inner join compra Con on CC.compra_id = Con.id where Con.id = "+idCompra);
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                totalPago= Float.parseFloat(rs.getString("totalPagado"));
            }
            
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    return totalPago;
}
private boolean esFlotante(String abono){
     boolean entero = false;
    try {
        Float.parseFloat(abono);
        entero = true;
    } catch (Exception e) {
    }
    return entero;
}
private String getUltimoIdCredito(){
  String id = "";
       try {
            conexion.EjecutarConsulta("SELECT MAX(id)As ultimo FROM credito");
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                id = rs.getString("ultimo");
            }
            
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return id;
}
private void crearCredito_has_compra(String idCompra,String idCredito){
    conexion.EjecutarInstruccion("insert into credito_has_compra(credito_id,compra_id)\n"+
            "values("+idCredito+","+idCompra+")");
}
private void crearCredito(String abono, String fecha, String idProveedor){
    conexion.EjecutarInstruccion("insert into credito(abono,fecha,proveedor_id)\n"+
            "values("+abono+",'"+fecha+"',"+idProveedor+")");
}

    private void radioDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDeudaActionPerformed
       
    }//GEN-LAST:event_radioDeudaActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
       tabbedCompra.setSelectedIndex(0);
       tabbedCompra.setEnabledAt(1,false);
       tabbedCompra.setEnabledAt(0,true);
       botonRegresar.setEnabled(false);
       botonDetalle.setEnabled(true);
       botonPagar.setEnabled(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonCargarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarIdActionPerformed
        String consulta = "", parametro,fechaInicio, fechaFinal,cadena="",id="",extra="",entrada = "";
        if(radioDeuda.isSelected()){
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n" +
"inner join compra C on C.id = CC.compra_id\n" +
"inner join credito Cre on Cre.id = CC.credito_id  group by C.id having total>totalPagado";
            entrada = " and ";
        }
        if(radioSaldo.isSelected()){
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n" +
"inner join compra C on C.id = CC.compra_id\n" +
"inner join credito Cre on Cre.id = CC.credito_id  group by C.id having total<=totalPagado";
            entrada = " and ";
            
        }
        
                cadena = " C.no_factura";
                id =  "C.id ";
                cargarTablaId(consulta, txtId.getText(), cadena,id, extra,entrada,tablaCompra, titulos);
           
    }//GEN-LAST:event_botonCargarIdActionPerformed

    private void radioSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSaldoActionPerformed
       botonPagar.setEnabled(false);
    }//GEN-LAST:event_radioSaldoActionPerformed

    private void comoboCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoboCargarActionPerformed
        if(comoboCargar.getSelectedIndex() == 0){
           //desactivar modulo cargar por rango de fecha
           botonCragarFecha.setEnabled(false);
           txtFechaF.setText("");
           txtFechaI.setText("");
           
           txtFechaF.setEnabled(false);
           txtFechaI.setEnabled(false);
           //activar modulo cargar por id o numero
           botonCargarId.setEnabled(true);
           txtId.setEnabled(true);
        }
        else{
            //desactivar modulo id o numero
            botonCargarId.setEnabled(false);
            txtId.setEnabled(false);
            txtId.setText("");
            //activar boton cargar rango de fecha 
             botonCragarFecha.setEnabled(true);
             txtFechaF.setEnabled(true);
             txtFechaI.setEnabled(true);
        }
    }//GEN-LAST:event_comoboCargarActionPerformed

    private void botonCragarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCragarFechaActionPerformed
        String consulta = "", fechaInicial,fechaFinal;
        fechaFinal = txtFechaF.getText();
        fechaInicial = txtFechaI.getText();
        if(radioDeuda.isSelected()){
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n" +
"inner join compra C on C.id = CC.compra_id\n" +
"inner join credito Cre on Cre.id = CC.credito_id  group by C.id  having C.fecha between '"+fechaInicial+"' and '"+fechaFinal+"' and total > totalPagado";
        }
        if(radioSaldo.isSelected()){
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n" +
"inner join compra C on C.id = CC.compra_id\n" +
"inner join credito Cre on Cre.id = CC.credito_id  group by C.id  having C.fecha between '"+fechaInicial+"' and '"+fechaFinal+"' and total <= totalPagado";
        }
        cargarTablaFecha(consulta, tablaCompra, titulos);
    }//GEN-LAST:event_botonCragarFechaActionPerformed

    private void botonDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetalleActionPerformed
       int fila = tablaCompra.getSelectedRow();
       String idCompra,consulta;
       //ver si es una compra en deuda 
       if(fila>=0){
           if(radioDeuda.isSelected()){
               botonPagar.setEnabled(true);
           }
           
       //datos especificos de la compra
       idCompra =String.valueOf(tablaCompra.getValueAt(fila,0));
       lableIdCompra.setText(idCompra);
       labelTotal.setText(String.valueOf(tablaCompra.getValueAt(fila,2)));
       labelFechaC.setText(String.valueOf(tablaCompra.getValueAt(fila,1)));
       
       labelSubTotal.setText(""+sumaPagas(lableIdCompra.getText()));
       //activar el panel de detalle 
       tabbedCompra.setSelectedIndex(1);
       tabbedCompra.setEnabledAt(1,true);
       tabbedCompra.setEnabledAt(0,false);
       botonRegresar.setEnabled(true);
       botonDetalle.setEnabled(false);
       //datos del proveedor de la compra 
       datosProveedor(String.valueOf(tablaCompra.getValueAt(fila,4)));
       
       consulta = "select M.id,M.nombre,M.alto,M.ancho,M.cantidad,M.color,M.tipo,M.costo,DC.cantidad as contidad_comprada from detalle_compra DC \n" +
"inner join compra C on C.id = DC.compra_id\n" +
"inner join material M on M.id = DC.material_id ";
           cargarTablaId(consulta,idCompra," C.no_factura ", " C.id ",""," where ", tablaMat, titulosMat);
           consultaTablaCredito(idCompra);
       
         
       }
       else{
           JOptionPane.showMessageDialog(null,"Seleccione un compra","Advertencia",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_botonDetalleActionPerformed

    private void botonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarActionPerformed
        float totalCompra = Float.parseFloat(labelTotal.getText());
         
        String ultimoPagoId;
        String pago = JOptionPane.showInputDialog("Ingrese el pago");
        if(esFlotante(pago)){
          crearCredito(pago,fecha(),labelIdProveedor.getText()); //crear el pago 
          ultimoPagoId = getUltimoIdCredito();//obtener el ultimo id de pago
          crearCredito_has_compra(lableIdCompra.getText(),ultimoPagoId);//hacer la relacion de pago con la compra 
          if(sumaPagas(lableIdCompra.getText())>=totalCompra){//ver si el total de pago es mayor o igual al total de la compra 
              JOptionPane.showMessageDialog(null,"La compra se ha pagado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
              botonPagar.setEnabled(false);//se bloque el boton de pago si la suma de los pagos es mayor igual al total de la compra
          }
            consultaTablaCredito(lableIdCompra.getText());//volvemos a cargar la tabla de pagos o credito
            labelSubTotal.setText(""+sumaPagas(lableIdCompra.getText()));
        }
        else{
            JOptionPane.showMessageDialog(null,"El valor que ingreso no es un digito","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonPagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarId;
    private javax.swing.JButton botonCragarFecha;
    private javax.swing.JButton botonDetalle;
    private javax.swing.JButton botonPagar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> comoboCargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFechaC;
    private javax.swing.JLabel labelIdProveedor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumCuenta;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel lableIdCompra;
    private javax.swing.JRadioButton radioDeuda;
    private javax.swing.JRadioButton radioSaldo;
    private javax.swing.JTabbedPane tabbedCompra;
    private javax.swing.JTable tablaCompra;
    private javax.swing.JTable tablaMat;
    private javax.swing.JTable tablaPago;
    private javax.swing.JTextField txtFechaF;
    private javax.swing.JTextField txtFechaI;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
