/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import java.awt.event.WindowEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class Material extends javax.swing.JFrame {
     
     private  String[]  titulos = {"Id","Nombre","Alto","Ancho","Cantidad","Color","Tipo"};
     private String ID = "", Tipo = "",Alto1 ="",nombreTemp = "";
     private int opcion;
     private float Alto;
     
     public Material() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Material");
         
        ventanaNuevo.setTitle("Nuevo Material");
        ventanaNuevo.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
       // setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaNuevo = new javax.swing.JDialog();
        panelNuevo = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonAceptarD = new javax.swing.JButton();
        botonCancelarD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonRadio = new javax.swing.JRadioButton();
        comboTipo = new javax.swing.JComboBox<>();
        panelMaterial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMateriales = new javax.swing.JTable();
        PanelMaterial2 = new javax.swing.JPanel();
        botonCargar = new javax.swing.JButton();
        cuadroTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonNuevo = new javax.swing.JButton();
        botonEditar = new javax.swing.JToggleButton();
        botonEliminar = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();

        ventanaNuevo.setSize(new java.awt.Dimension(498, 410));

        panelNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelNuevo.setPreferredSize(new java.awt.Dimension(404, 522));

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel5.setText("Cantidad");

        jLabel6.setText("Color");

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Obligatorio");

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Obligatorio");

        javax.swing.GroupLayout panelNuevoLayout = new javax.swing.GroupLayout(panelNuevo);
        panelNuevo.setLayout(panelNuevoLayout);
        panelNuevoLayout.setHorizontalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoLayout.createSequentialGroup()
                        .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(32, 32, 32)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtColor, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtCantidad))
                .addGap(43, 43, 43))
        );
        panelNuevoLayout.setVerticalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGap(37, 37, 37)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAceptarD.setText("Aceptar");
        botonAceptarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarDActionPerformed(evt);
            }
        });

        botonCancelarD.setText("Cancelar ");
        botonCancelarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(botonAceptarD)
                .addGap(72, 72, 72)
                .addComponent(botonCancelarD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelarD)
                    .addComponent(botonAceptarD))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonRadio.setText("Tipo");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carta", "Oficio" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(botonRadio)
                .addGap(92, 92, 92)
                .addComponent(comboTipo, 0, 158, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRadio))
                .addContainerGap())
        );

        javax.swing.GroupLayout ventanaNuevoLayout = new javax.swing.GroupLayout(ventanaNuevo.getContentPane());
        ventanaNuevo.getContentPane().setLayout(ventanaNuevoLayout);
        ventanaNuevoLayout.setHorizontalGroup(
            ventanaNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
        );
        ventanaNuevoLayout.setVerticalGroup(
            ventanaNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMaterialesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMateriales);

        javax.swing.GroupLayout panelMaterialLayout = new javax.swing.GroupLayout(panelMaterial);
        panelMaterial.setLayout(panelMaterialLayout);
        panelMaterialLayout.setHorizontalGroup(
            panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelMaterialLayout.setVerticalGroup(
            panelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelMaterial2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonCargar.setText("Cargar");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });

        cuadroTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cuadroTextoKeyPressed(evt);
            }
        });

        jLabel1.setText("Id / Nombre");

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonReporte.setText("Reporte");
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMaterial2Layout = new javax.swing.GroupLayout(PanelMaterial2);
        PanelMaterial2.setLayout(PanelMaterial2Layout);
        PanelMaterial2Layout.setHorizontalGroup(
            PanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMaterial2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(botonCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMaterial2Layout.createSequentialGroup()
                        .addComponent(cuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(botonNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(botonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminar))
                    .addGroup(PanelMaterial2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonReporte)))
                .addContainerGap())
        );
        PanelMaterial2Layout.setVerticalGroup(
            PanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMaterial2Layout.createSequentialGroup()
                .addGroup(PanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMaterial2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(PanelMaterial2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonReporte)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevo)
                    .addComponent(botonEditar)
                    .addComponent(botonEliminar)
                    .addComponent(botonCargar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Boton ingresar un nuevo material
    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        opcion = 1;
        ventanaNuevo.setVisible(true);
        ventanaNuevo.setLocationRelativeTo(null);
        ventanaNuevo.setTitle("Nuevo material");
        limpiarTxt();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void cuadroTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuadroTextoKeyPressed

    }//GEN-LAST:event_cuadroTextoKeyPressed
//Cargar la base de datos en la tabla de la ventana. 
    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
       String campo = cuadroTexto.getText();
        String where = "";
        if(!"".equals(campo)){
            where = "WHERE id = '"+campo+"' OR nombre = '"+campo+"'";
        }
         try {
         DefaultTableModel modelo = new DefaultTableModel(null,titulos);
         tablaMateriales.setModel(modelo);
         ConexionMySQL conexion = new ConexionMySQL("localhost","3305","proyectobd3","root","xela2020");
         conexion.EjecutarConsulta("SELECT id, nombre, alto, ancho, cantidad, color, tipo FROM material "+where+" "+"ORDER BY cantidad");
            
            ResultSet rs = conexion.getResulSet();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
              
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i=0; i <cantidadColumnas ; i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,"Error de conexion","Error",JOptionPane.ERROR_MESSAGE);
         System.out.println(ex.getMessage());
        
    }
    }//GEN-LAST:event_botonCargarActionPerformed
private void limpiarTxt(){
      txtNombre.setText("");
      txtCantidad.setText("");
      txtColor.setText("");
      Tipo = "";
      botonRadio.setSelected(false);
      comboTipo.setSelectedIndex(0);
}
 private void cerrarDialogNuevo(){
     ventanaNuevo.setVisible(false);
      limpiarTxt();
      ID = "";
      ventanaNuevo.dispose();
}
 private int existePorNombre(String nombreBuscar){
        int id = -1;
     ConexionMySQL conexion1 = new ConexionMySQL("localhost","3305","proyectobd3","root","xela2020");
            conexion1.EjecutarConsulta("SELECT * FROM material WHERE nombre ="+"'"+nombreBuscar+"'");
            ResultSet rs = conexion1.getResulSet();
            try {
                while(rs.next()){
                  id = Integer.parseInt(rs.getString("id"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Material.class.getName()).log(Level.SEVERE, null, ex);
            }
     return id;
 }
 private void insertarMaterial(String nombre, String alto, String ancho, String cantidad, String color, String tipo){
     //se pregunta si esta deacuerdo con los datos del material
                   int res = JOptionPane.showConfirmDialog(rootPane,"¿Esta deacuerdo con el material? \n"+"Nombre: "+nombre
                    +"\nCantidad: "+cantidad+"\nColor: "+color+"\nTipo: "+tipo+"\nDimensiones: "+alto+"cm x "+ancho+"cm","Advertencia",
                    JOptionPane.YES_NO_OPTION);
                   if(res == 0){//si esta deacuerdo con los datos del material 
                     //se inserta el material en la base de datos.
                     ConexionMySQL conexion = new ConexionMySQL("localhost","3305","proyectobd3","root","xela2020");
                     conexion.EjecutarInstruccion("INSERT INTO material(nombre,alto,ancho,cantidad,color,tipo)"  
                             + "VALUES ('"+nombre+"',"+alto+","+ancho+","+cantidad+",'"+color+"' ,'"+tipo+"')"); 
                
                //Mensaje que describe que el material ingreso en el sistema      
                JOptionPane.showMessageDialog(null,"Material Ingresado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                cerrarDialogNuevo(); 
                   }
 }
 private void modificarMaterial(String nombre, String alto, String ancho, String cantidad, String color, String tipo){
     //se pregunta si esta deacuerdo con los datos del material
                   int res = JOptionPane.showConfirmDialog(rootPane,"¿Esta deacuerdo con la modificacion del material? \n"+"Nombre: "+nombre
                    +"\nCantidad: "+cantidad+"\nColor: "+color+"\nTipo: "+tipo+"\nDimensiones: "+alto+"cm x "+ancho+"cm","Advertencia",
                    JOptionPane.YES_NO_OPTION);
                   if(res == 0){//si esta deacuerdo con los datos del material 
                     //se inserta el material en la base de datos.
                     ConexionMySQL conexion = new ConexionMySQL("localhost","3305","proyectobd3","root","xela2020");
                     conexion.EjecutarInstruccion("UPDATE material SET nombre = '"+nombre+"',"+"alto = "+alto+","+
                             "ancho = "+ancho+",cantidad = "+cantidad+",color = '"+color+"',tipo = '"+tipo+"'"+"WHERE id = "+ID); 
                
                //Mensaje que describe que el material ingreso en el sistema      
                JOptionPane.showMessageDialog(null,"Material Modificado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                cerrarDialogNuevo(); 
                   }
 }
//boton cancelar dialog
    private void botonCancelarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarDActionPerformed
      cerrarDialogNuevo();
    }//GEN-LAST:event_botonCancelarDActionPerformed
//Haceptar solo numeros 
    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
      char validar = evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null,"Solo ingrese numeros","Error",JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_txtCantidadKeyTyped
private void aceptarBoton(int opcion1){
        String tipo="NULL", nombre = "",alto = "NULL",ancho ="NULL";
        int idNombreActual, idNombreAnterior;
            if(txtNombre.getText().length() == 0 || txtCantidad.getText().length() == 0 ){ // ver si los campos nombre y cantidad estan llenos 
                JOptionPane.showMessageDialog(null,"Llene los campos obligatorios","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{//si los campos obligatorios estan llenos.  
                idNombreActual = existePorNombre(txtNombre.getText());
                // si la opcion es de insertar un nuevo material
               if(opcion == 1){
                  if(idNombreActual < 0){//si el nombre del material no existe
                  if(botonRadio.isSelected()){//Si la opcion tipo esta habilitada
                   if(comboTipo.getSelectedIndex() == 0){// si es carta 
                       alto ="27.94";
                       ancho ="21.59";
                       tipo = "Carta";
                   } 
                   else{// si es oficio
                       alto ="33";
                       ancho ="21.64";
                       tipo = "Oficio";     
                   }
                    
                }
                  
                       insertarMaterial(txtNombre.getText(), alto, ancho, txtCantidad.getText(),txtColor.getText(), tipo);//insertamos los materiales 
                }//fin del if(nombre == "")
                else{
                    JOptionPane.showMessageDialog(null,"El nombre del producto ya existe","Error",JOptionPane.ERROR_MESSAGE);
                } 
               }//fin del if(opcion ==1)
               else{
                   idNombreAnterior = existePorNombre(nombreTemp);
                 if((idNombreAnterior == idNombreActual) || (idNombreAnterior!=idNombreActual && idNombreActual <0)){//si el nombre del material no existe
                  if(botonRadio.isSelected()){//Si la opcion tipo esta habilitada
                   if(comboTipo.getSelectedIndex() == 0){// si es carta 
                       alto ="27.94";
                       ancho ="21.59";
                       tipo = "Carta";
                   } 
                   else{// si es oficio
                       alto ="33";
                       ancho ="21.64";
                       tipo = "Oficio";     
                   }
                    
                }
                  
                   modificarMaterial(txtNombre.getText(), alto, ancho, txtCantidad.getText(),txtColor.getText(), tipo);//insertamos los materiales 
                }//fin del if(nombre == "")
                else{
                    JOptionPane.showMessageDialog(null,"El nombre del producto ya existe","Error",JOptionPane.ERROR_MESSAGE);
                }
               }
                 
                      
            } //fin del else de los campos llenos 
}
//Boton aceptar de la ventana nuevo
    private void botonAceptarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarDActionPerformed
              aceptarBoton(opcion);
    }//GEN-LAST:event_botonAceptarDActionPerformed
//Se hace el reporte de la tabla del modulo de material
    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
        
         try {
              ConexionMySQL conexion = new ConexionMySQL("localhost","3305","proyectobd3","root","xela2020");
              Connection con = conexion.getConexion();
             InputStream archivo=getClass().getResourceAsStream("/Reporte/Material.jrxml");
             JasperDesign dise = JRXmlLoader.load(archivo);
             JasperReport jr = JasperCompileManager.compileReport(dise);
             JasperPrint jp = JasperFillManager.fillReport(jr,null,con);
             JasperViewer.viewReport(jp); 
         } catch (JRException ex) {
             Logger.getLogger(Material.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_botonReporteActionPerformed
//boton eliminar 
    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
           if(ID == ""){
            JOptionPane.showMessageDialog(rootPane,"Seleccione un producto","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            String nombre="",alto="",ancho="", cantidad="",color="",tipo="", id="";
        ConexionMySQL conexion = new ConexionMySQL("localhost","3305","proyectobd3","root","xela2020");
        conexion.EjecutarConsulta("SELECT * FROM material WHERE id = "+ID);
        ResultSet rs = conexion.getResulSet();
         try {
             
             while(rs.next()){
                 id = rs.getString("id");
                 nombre = rs.getString("nombre");
                 alto = rs.getString("alto");
                 ancho = rs.getString("ancho");
                 cantidad = rs.getString("cantidad");
                 color = rs.getString("color");
                 tipo = rs.getString("tipo");
             }
             
               int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar? \n"+"Nombre: "+nombre+"\n"
             +"Alto: "+alto+"\n"+"Ancho: "+ancho+"\n"+"Cantidad: "+cantidad+"\n"+"Color: "+color+"\n"+"Tipo: "+tipo,"Advertencia",JOptionPane.YES_NO_OPTION);   
             if(resp == 0){// si acepta que se elimine el material
                 conexion.EjecutarInstruccion("DELETE FROM material WHERE id = "+id);
                 JOptionPane.showMessageDialog(rootPane,"El producto se elimino","Mensaje",JOptionPane.INFORMATION_MESSAGE);    
             }
              ID = ""; 
         } catch (SQLException ex) {
             Logger.getLogger(Material.class.getName()).log(Level.SEVERE, null, ex);
         }
        }// fin del elese principal
    }//GEN-LAST:event_botonEliminarActionPerformed

//accion boton aceptar de la ventana de dialogo eliminar 
    private void tablaMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMaterialesMouseClicked

      int seleccion = tablaMateriales.rowAtPoint(evt.getPoint());
      ID = String.valueOf(tablaMateriales.getValueAt(seleccion,0));
      txtNombre.setText(String.valueOf(tablaMateriales.getValueAt(seleccion,1)));
      nombreTemp = String.valueOf(tablaMateriales.getValueAt(seleccion,1));//se hace una copia del nombre, anterior a la edicion 
      txtCantidad.setText(String.valueOf(tablaMateriales.getValueAt(seleccion,4)));
      txtColor.setText(String.valueOf(tablaMateriales.getValueAt(seleccion,5)));
      Tipo = String.valueOf(tablaMateriales.getValueAt(seleccion,6));
      Alto1 = String.valueOf(tablaMateriales.getValueAt(seleccion,2));
      if(Alto1 != "null"){
          Alto = (float) tablaMateriales.getValueAt(seleccion,2);
      }
      else{
          Alto = 0;
      }
    }//GEN-LAST:event_tablaMaterialesMouseClicked

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
       // System.out.println(ID);
        if(ID!=""){
       opcion = 0;
       ventanaNuevo.setVisible(true);
       ventanaNuevo.setLocationRelativeTo(null);
       ventanaNuevo.setTitle("Editar Material");
           //System.out.println(Tipo);
           //System.out.println(Alto);
           if(Alto !=0){
               botonRadio.setSelected(true);
               if(Alto == 33.0){
                   comboTipo.setSelectedIndex(1);
               }
           }
       }
       else{
           JOptionPane.showMessageDialog(rootPane,"Seleccione un material","Error",JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_botonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Material().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMaterial2;
    private javax.swing.JButton botonAceptarD;
    private javax.swing.JButton botonCancelarD;
    private javax.swing.JButton botonCargar;
    private javax.swing.JToggleButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JRadioButton botonRadio;
    private javax.swing.JButton botonReporte;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JTextField cuadroTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMaterial;
    private javax.swing.JPanel panelNuevo;
    private javax.swing.JTable tablaMateriales;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JDialog ventanaNuevo;
    // End of variables declaration//GEN-END:variables
}
