/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class Producto2 extends javax.swing.JInternalFrame {

    private ConexionMySQL conexion;
    private  String[]  titulos = {"Id","descipcion","nombre","precio","Costo Produccion"},titulosMaterial = {"Id","Nombre","Existencias","Costo","Cantidad","Subtotal"},
            tituloMaterialPro = {"Id","Nombre","Existencias","Tipo","Costo","Cantidad"};
    private String localhost = "localhost",puerto = "3305",baseDeDatos = "proyectobd3",usuario ="root",contra = "xela2020";
    private DefaultTableModel  modelo, modelo2;
    private int tipoUsuario, nuevoUeditar;
    private Modulo producto;
    public Producto2(int tipo) {
        initComponents();
        
        conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
        botonCancelar.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonRegresar.setEnabled(false);
        
        tabbed.setEnabledAt(1,false);
        tabbed.setEnabledAt(2,false);
        labelNombre.setText("");
        labelExistencia.setText("");
        labelCosto.setText("");
        labelCostoProduccion.setText("0");
        producto = new Modulo();
        modelo = new DefaultTableModel(null,titulosMaterial);
        this.tablaMateriales.setModel(modelo);
        this.tipoUsuario = tipo;
        
        if(this.tipoUsuario == 0){
            botonNuevo.setEnabled(false);
            botonEditar.setEnabled(false);
            botonReporte.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Cantidad = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Eliminar = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        menuItemQuitar = new javax.swing.JMenuItem();
        tabbed = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        botonCargar = new javax.swing.JButton();
        txtCargar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMateriales = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        botonCargarMaterial = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        botonRemover = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelExistencia = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelCosto = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        botonAnadir = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCantidadMaterial = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        labelCostoProduccion = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaMaterialesPro = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescripcionPro = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelIDPro = new javax.swing.JLabel();
        labelNombrePro = new javax.swing.JLabel();
        labelPresioPro = new javax.swing.JLabel();
        labelCostoPro = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        labelCantiMateriales = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtNombreEditar = new javax.swing.JTextField();
        txtPrecioEditar = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAreaEditar = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        labelIdProEdit = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labelCostoProEdit = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        botonAnadirEditar = new javax.swing.JButton();
        txtIdMaterialEdit = new javax.swing.JTextField();
        botonCargarEdit = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        botonRemoverEdit = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        txtCantidadEdit = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        labelNombreMaterial = new javax.swing.JLabel();
        labelCostoMaterial = new javax.swing.JLabel();
        labelExistenciaMaterial = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelSubTotalEdit = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaNuevoMaterial = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        labelTotalEdit = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();
        botonDetalle = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        Cantidad.setText("Editar Cantidad");
        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Cantidad);
        jPopupMenu1.add(jSeparator1);

        Eliminar.setText("Eliminar");
        jPopupMenu1.add(Eliminar);

        menuItemQuitar.setText("Quitar");
        menuItemQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuitarActionPerformed(evt);
            }
        });
        jPopupMenu2.add(menuItemQuitar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProducto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonCargar.setText("Cargar");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCargar)
                .addGap(18, 18, 18)
                .addComponent(txtCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCargar)
                    .addComponent(txtCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed.addTab("Producto", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Datos producto");

        jLabel2.setText("NOMBRE: ");

        jLabel3.setText("PRECIO:");

        jLabel4.setText("DESCRIPCION:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaMateriales);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonCargarMaterial.setText("Cargar");
        botonCargarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarMaterialActionPerformed(evt);
            }
        });

        botonRemover.setText("Remover");
        botonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoverActionPerformed(evt);
            }
        });

        jLabel7.setText("ID MATERIAL :");

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Del Material"));

        jLabel9.setText("NOMBRE:");

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombre.setText("jLabel10");

        jLabel11.setText("EXISTENCIAS:");

        labelExistencia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelExistencia.setText("jLabel13");

        jLabel12.setText("COSTO:");

        labelCosto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCosto.setText("jLabel14");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExistencia))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombre)))
                .addGap(79, 79, 79)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCosto)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelNombre)
                    .addComponent(jLabel12)
                    .addComponent(labelCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelExistencia))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCargarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(botonRemover)))
                .addGap(71, 71, 71))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarMaterial)
                    .addComponent(botonRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonAnadir.setText("Añadir");
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });

        botonQuitar.setText("Quitar");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        jLabel8.setText("CANTIDAD:");

        jLabel16.setText("COSTO PRODUCCION:");

        labelCostoProduccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCostoProduccion.setText("jLabel17");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(botonAnadir)
                .addGap(18, 18, 18)
                .addComponent(botonQuitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCostoProduccion)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnadir)
                    .addComponent(botonQuitar)
                    .addComponent(jLabel8)
                    .addComponent(txtCantidadMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCostoProduccion))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed.addTab("Nuevo", jPanel2);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Materiales"));

        tablaMaterialesPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMaterialesPro.setComponentPopupMenu(jPopupMenu1);
        jScrollPane4.setViewportView(tablaMaterialesPro);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Producto"));

        jLabel14.setText("ID:");

        jLabel17.setText("NOMBRE:");

        jLabel19.setText("DESCRIPCION:");

        txtDescripcionPro.setColumns(20);
        txtDescripcionPro.setRows(5);
        jScrollPane5.setViewportView(txtDescripcionPro);

        jLabel18.setText("PRESIO: ");

        jLabel20.setText("COSTO DE PRODUCCION:");

        labelIDPro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelIDPro.setText("jLabel21");

        labelNombrePro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombrePro.setText("jLabel22");

        labelPresioPro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelPresioPro.setText("jLabel23");

        labelCostoPro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCostoPro.setText("jLabel24");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(labelIDPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNombrePro)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPresioPro))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(labelCostoPro)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19)
                            .addComponent(labelIDPro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(labelNombrePro)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labelPresioPro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(labelCostoPro))
                .addGap(23, 23, 23))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setText("CANTIDAD MATERIALES:");

        labelCantiMateriales.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCantiMateriales.setText("jLabel22");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCantiMateriales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(labelCantiMateriales))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed.addTab("Detalle", jPanel10);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Producto"));

        txtAreaEditar.setColumns(20);
        txtAreaEditar.setRows(5);
        jScrollPane6.setViewportView(txtAreaEditar);

        jLabel22.setText("NOMBRE:");

        jLabel23.setText("PRECIO:");

        jLabel24.setText("DESCRIPCION:");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 0));
        jLabel25.setText("*");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 51, 0));
        jLabel26.setText("*");

        jLabel27.setText("ID:");

        labelIdProEdit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelIdProEdit.setText("jLabel28");

        jLabel28.setText("COSTO PRODUCCION:");

        labelCostoProEdit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCostoProEdit.setText("jLabel34");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelIdProEdit)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCostoProEdit))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(txtPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(labelIdProEdit)
                    .addComponent(jLabel28)
                    .addComponent(labelCostoProEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addGap(32, 32, 32)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonAnadirEditar.setText("Añadir");
        botonAnadirEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirEditarActionPerformed(evt);
            }
        });

        botonCargarEdit.setText("Cargar");
        botonCargarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarEditActionPerformed(evt);
            }
        });

        jLabel29.setText("ID MATERIAL:");

        botonRemoverEdit.setText("Remover");
        botonRemoverEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoverEditActionPerformed(evt);
            }
        });

        jLabel31.setText("CANTIDAD:");

        txtCantidadEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadEditKeyReleased(evt);
            }
        });

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Material"));

        jLabel30.setText("NOMBRE:");

        jLabel32.setText("COSTO:");

        jLabel33.setText("EXISTENCIAS:");

        labelNombreMaterial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombreMaterial.setText("null");

        labelCostoMaterial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCostoMaterial.setText("null");

        labelExistenciaMaterial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelExistenciaMaterial.setText("null");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(labelNombreMaterial))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCostoMaterial)
                            .addComponent(labelExistenciaMaterial))))
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(labelNombreMaterial))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(labelCostoMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(labelExistenciaMaterial))
                .addGap(20, 20, 20))
        );

        jLabel10.setText("SUBTOTAL:");

        labelSubTotalEdit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelSubTotalEdit.setText("0");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel29)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(botonCargarEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRemoverEdit))
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIdMaterialEdit)
                        .addComponent(txtCantidadEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addComponent(labelSubTotalEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAnadirEditar))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonCargarEdit)
                        .addComponent(botonRemoverEdit))
                    .addComponent(botonAnadirEditar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtIdMaterialEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelSubTotalEdit))
                        .addGap(24, 24, 24))))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nuevo Material"));

        tablaNuevoMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaNuevoMaterial.setComponentPopupMenu(jPopupMenu2);
        jScrollPane7.setViewportView(tablaNuevoMaterial);

        jLabel15.setText("TOTAL:");

        labelTotalEdit.setBackground(new java.awt.Color(0, 0, 0));
        labelTotalEdit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTotalEdit.setText("0");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalEdit)
                .addGap(35, 35, 35))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(labelTotalEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbed.addTab("Editar", jPanel14);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonReporte.setText("Reporte");
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });

        botonDetalle.setText("Detalle");
        botonDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetalleActionPerformed(evt);
            }
        });

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonNuevo)
                .addGap(18, 18, 18)
                .addComponent(botonEditar)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar)
                .addGap(60, 60, 60)
                .addComponent(botonDetalle)
                .addGap(18, 18, 18)
                .addComponent(botonRegresar)
                .addGap(81, 81, 81)
                .addComponent(botonGuardar)
                .addGap(26, 26, 26)
                .addComponent(botonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(botonReporte)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void limpiarPanelProducto(){
    txtDescripcion.setText("");
    txtNombre.setText("");
    txtPrecio.setText("");
    labelCostoProduccion.setText("0");
    
}
private void limpiarPanelMaterial(){
    labelCosto.setText("");
    labelNombre.setText("");
    labelExistencia.setText("");
    txtId.setText("");
    txtId.setEnabled(true);
    txtCantidadMaterial.setText("");
   
}

private void activarPanel(){
    botonEditar.setEnabled(false);
    botonNuevo.setEnabled(false);
    botonReporte.setEnabled(false);
    botonDetalle.setEnabled(false);
    botonAnadir.setEnabled(false);
    botonRemover.setEnabled(false);
    botonQuitar.setEnabled(false);
    botonRegresar.setEnabled(false);
    botonEliminar.setEnabled(false);
    botonCancelar.setEnabled(true);
    botonGuardar.setEnabled(true);
  
    tabbed.setEnabledAt(1,true);
    tabbed.setEnabledAt(0,false);
    tabbed.setSelectedIndex(1);
    
}
private boolean existeMaterial(String parametro,String tabla, String formaParametro){
    boolean existe = false;
        try {
            conexion.EjecutarConsulta("SELECT COUNT(*) FROM "+tabla +" WHERE "+formaParametro+" = "+parametro+"");
            ResultSet rs = conexion.getResulSet();
            rs.next();
            if(rs.getInt(1)>0){
                existe = true;
            }   
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return existe; 
}
private void cargarTablaId(String consulta, String parametroEntrada, String formaParametro, String formaId, String extra,String entrada,JTable tabla, String[] titulo){
    TablaId tablaLlena = new TablaId(tabla);
    tablaLlena.llenarTable(consulta, parametroEntrada, formaParametro, formaId, extra, entrada, titulo);
    tabla = tablaLlena.getTabla();
}
private boolean existeRegistro(String parametro,String tabla, String formaParametro){
     boolean existe = false;
        try {
            conexion.EjecutarConsulta("SELECT COUNT(*) FROM "+tabla +" WHERE "+formaParametro+" = "+parametro+"");
            ResultSet rs = conexion.getResulSet();
            rs.next();
            if(rs.getInt(1)>0){
                existe = true;
            }   
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return existe;  
}
private void insertarEnTabla(String id, String nombre, String existencias, String costo, String cantidad,String subTotal){
     String []info =new String[6];
                        info[0] = id;
                        info[1] = nombre;
                        info[2] = existencias;
                        info[3] = costo;
                        info[4] = cantidad;
                        info[5] = subTotal;
                        modelo.addRow(info);
}
private void eliminarRegistroTabla(JTable tabla,DefaultTableModel modelo,JLabel total1 ){
    int fila = tabla.getSelectedRow();
    float total = Float.parseFloat(total1.getText()),subTotal;
        if(fila>=0){
            subTotal = Float.parseFloat(String.valueOf(tabla.getValueAt(fila,5)));
            modelo.removeRow(fila);
            total = total - subTotal;
            total1.setText(""+total);
        }
        else{
            JOptionPane.showMessageDialog(null,"Seleccione un material","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        
}
private void limpiarTabla(DefaultTableModel modelo, JTable tabla){
    int fila = tabla.getRowCount();
    for(int i = fila-1;i>=0;i--){
        modelo.removeRow(i);
    }
}
private boolean existeEnTabla(String id,JTable tabla){
     boolean existe = false;
     int iD;
     iD = Integer.parseInt(id);
        for(int i = 0; i<tabla.getRowCount();i++){
            if(iD == Integer.parseInt(String.valueOf(tabla.getValueAt(i,0))) ){
                existe = true;
            }
        }
        return existe;
}
private String getDato(String formaId, String id, String tabla, String parametro){
    String dato = "";
    ConexionMySQL conexion1 = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion1.EjecutarConsulta("SELECT * FROM "+tabla+" WHERE "+formaId+" = "+id);
            ResultSet rs = conexion1.getResulSet();
            try {
                while(rs.next()){
                  dato = rs.getString(parametro);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Producto2.class.getName()).log(Level.SEVERE, null, ex);
            }
    return dato; 
}
private boolean esFlotante(String abono){
     boolean entero = false;
    try {
        Float.parseFloat(abono);
        entero = true;
    } catch (Exception e) {
    }
    return entero;
}
private  boolean esEntero(String id){
    boolean entero = false;
    try {
        Integer.parseInt(id);
        entero = true;
    } catch (Exception e) {
    }
    return entero;
}
private void nuevoRegistro(String colummnas, String parametro, String tabla){
    conexion.EjecutarInstruccion("insert into "+tabla+" ("+colummnas+")\n"+
              "values("+parametro+")");
    
}
private String getUltimoIdProducto(){
    String id = "";
       try {
            conexion.EjecutarConsulta("SELECT MAX(id)As ultimo FROM producto");
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                id = rs.getString("ultimo");
            }
            
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return id;
}
private void relacionMaterialProducto(String idProducto){
    int fila = tablaMateriales.getRowCount();
    String colummnas = "producto_id,material_id,Cantidad",parametros;
    for(int i = 0;i<fila;i++){
        parametros =idProducto+","+String.valueOf(tablaMateriales.getValueAt(i,0))+","+String.valueOf(tablaMateriales.getValueAt(i,4));
        nuevoRegistro(colummnas, parametros,"producto_has_material");
    }
}
private void guardarNuevoProducto(){
    String idProducto;
                    if(txtNombre.getText().length()>0&&txtPrecio.getText().length()>0&&tablaMateriales.getRowCount()>0){
                     if(esFlotante(txtPrecio.getText())){
                         if(!existeRegistro("'"+txtNombre.getText()+"'","producto","nombre")){
                             String colummnasProducto = "descripcion,nombre,precio,costoProduccion",
                                     parametrosProducto = "'"+txtDescripcion.getText()+"','"+txtNombre.getText()+"',"+txtPrecio.getText()+","+labelCostoProduccion.getText();
                             
                             nuevoRegistro(colummnasProducto,parametrosProducto,"producto");
                             idProducto = getUltimoIdProducto();    
                             relacionMaterialProducto(idProducto);
                             JOptionPane.showMessageDialog(null,"Producto ingresado");
                             
                             limpiarPanelProducto();
                             limpiarPanelMaterial();
                             limpiarTabla(modelo, tablaMateriales);
                             tabbed.setEnabledAt(1,false);
                             tabbed.setEnabledAt(0,true);
                             tabbed.setSelectedIndex(0);
                             
                                botonEditar.setEnabled(true);
                                botonNuevo.setEnabled(true);
                                botonReporte.setEnabled(true);
                                botonDetalle.setEnabled(true);

                                botonCancelar.setEnabled(false);
                                botonGuardar.setEnabled(false);
                         }
                         else{
                             JOptionPane.showMessageDialog(null,"El nombre ya pertenece a un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
                     }
                     }
                     else{
                         JOptionPane.showMessageDialog(null,"Ingrese digitos en el campo de precio","Advertencia",JOptionPane.WARNING_MESSAGE);
                     }
                 }        
                 else{
                     JOptionPane.showMessageDialog(null,"Llene los campos de nombre y precio, e ingrese por lo menos un material","Advertencia",JOptionPane.WARNING_MESSAGE);
                 }
    
}
private void editarProucto(){
    
}
private void limpiarPanelMaterialEditar(){
        labelNombreMaterial.setText("null");
        labelCostoMaterial.setText("null");
        labelExistenciaMaterial.setText("null");
        labelSubTotalEdit.setText("0");
        
        txtIdMaterialEdit.setText("");
        txtCantidadEdit.setText("");
        txtCantidadEdit.setEnabled(false);
        txtIdMaterialEdit.setEnabled(true);
        
        botonAnadirEditar.setEnabled(false);
        botonRemoverEdit.setEnabled(false);
        botonCargarEdit.setEnabled(true);
}
    private void botonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoverActionPerformed
     limpiarPanelMaterial();
     botonRemover.setEnabled(false);
    }//GEN-LAST:event_botonRemoverActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
    if(nuevoUeditar == 1){
        botonEditar.setEnabled(true);
    botonNuevo.setEnabled(true);
    botonReporte.setEnabled(true);
    botonDetalle.setEnabled(true);
   
    
    botonCancelar.setEnabled(false);
    botonGuardar.setEnabled(false);
    
    tabbed.setEnabledAt(1,false);
    tabbed.setEnabledAt(0,true);
    tabbed.setSelectedIndex(0);
    limpiarPanelProducto();
    limpiarPanelMaterial();
    if(tablaMateriales.getRowCount()>0){
        limpiarTabla(modelo,tablaMateriales);
    }
    }
    else{
    botonEditar.setEnabled(true);
    botonNuevo.setEnabled(true);
    botonReporte.setEnabled(true);
    botonDetalle.setEnabled(true);
    botonEliminar.setEnabled(true);

    
    botonCancelar.setEnabled(false);
    botonGuardar.setEnabled(false);
    
    tabbed.setEnabledAt(3,false);
    tabbed.setEnabledAt(0,true);
    tabbed.setSelectedIndex(0);
    
    txtNombreEditar.setText("");
    txtPrecioEditar.setText("");
    txtAreaEditar.setText("");
    
   
    if(tablaNuevoMaterial.getRowCount()>0){
        limpiarTabla((DefaultTableModel) tablaNuevoMaterial.getModel(), tablaNuevoMaterial);
    }
    if(tablaMateriales.getRowCount()>0){
        limpiarTabla(modelo,tablaMateriales);
    }
        
    }
   
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        nuevoUeditar = 1;       
        activarPanel();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
          nuevoUeditar = 0;
          String consulta = "select M.id,M.nombre,M.cantidad as exsitencias,M.tipo,M.costo,PM.Cantidad  from producto_has_material PM\n" +
"inner join producto P on P.id = PM.producto_id\n" +
"inner join material M on M.id = PM.material_id where P.id = ", idProducto;
          int fila = tablaProducto.getSelectedRow();
          if(fila>=0){
              //preparacion para mover al panel editar
                botonEditar.setEnabled(false);
                botonNuevo.setEnabled(false);
                botonReporte.setEnabled(false);
                botonDetalle.setEnabled(false);
                botonEliminar.setEnabled(false);
                botonRemoverEdit.setEnabled(false);
                botonAnadirEditar.setEnabled(false);
                
                txtCantidadEdit.setEnabled(false);


                botonCancelar.setEnabled(true);
                botonGuardar.setEnabled(true);

                tabbed.setEnabledAt(0,false);
                tabbed.setEnabledAt(3,true);
                tabbed.setSelectedIndex(3);
                
                //pasar los datos del producto al panel editar
                
                txtNombreEditar.setText(String.valueOf(tablaProducto.getValueAt(fila,2)));
                txtPrecioEditar.setText(String.valueOf(tablaProducto.getValueAt(fila,3)));
                txtAreaEditar.setText(String.valueOf(tablaProducto.getValueAt(fila,1)));
                idProducto = String.valueOf(tablaProducto.getValueAt(fila,0));
                labelIdProEdit.setText(idProducto);
                labelCostoProEdit.setText(String.valueOf(tablaProducto.getValueAt(fila,4)));
               //tabla nuevo material
                modelo2 = new DefaultTableModel(null,titulosMaterial);
                tablaNuevoMaterial.setModel(modelo2);
                
                
                
          }
          else{
              JOptionPane.showMessageDialog(null,"Seleccione un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
                  if(nuevoUeditar == 1){
                      guardarNuevoProducto();
                  }
                  else{
                      
                  }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
try {
            //ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
              Connection con = conexion.getConexion();
             InputStream archivo=getClass().getResourceAsStream("/Reporte/productos.jrxml");
             JasperDesign dise = JRXmlLoader.load(archivo);
             JasperReport jr = JasperCompileManager.compileReport(dise);
             JasperPrint jp = JasperFillManager.fillReport(jr,null,con);
             JasperViewer.viewReport(jp,false); 
         } catch (JRException ex) {
             Logger.getLogger(Producto2.class.getName()).log(Level.SEVERE, null, ex);
         }      
    }//GEN-LAST:event_botonReporteActionPerformed

    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
      String consulta = "select * from producto";
        cargarTablaId(consulta, txtCargar.getText(),"nombre","id","", "where", tablaProducto, titulos);
    }//GEN-LAST:event_botonCargarActionPerformed

    private void botonCargarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarMaterialActionPerformed
               String nombre, existencia, costo;
                if(txtId.getText().length()>0){
                   if(esEntero(txtId.getText())){
                       if(existeRegistro(txtId.getText(),"material","id")){
                           txtId.setEnabled(false);
                           botonAnadir.setEnabled(true);
                           botonRemover.setEnabled(true);
                           labelNombre.setText(getDato("id",txtId.getText(),"material","nombre"));
                           labelExistencia.setText(getDato("id",txtId.getText(),"material","cantidad"));
                           labelCosto.setText(getDato("id",txtId.getText(),"material","costo"));
                           
                           
                       }
                       else{
                           JOptionPane.showMessageDialog(null,"El material no existe","Advertencia",JOptionPane.WARNING_MESSAGE);
                       }
                   }
                   else{
                       JOptionPane.showMessageDialog(null,"Solo ingrese digitos","Advertencia",JOptionPane.WARNING_MESSAGE);
                   }
               }
               else{
                   JOptionPane.showMessageDialog(null,"Llene el campo de ID","Advertencia",JOptionPane.WARNING_MESSAGE);
    }
                   
    }//GEN-LAST:event_botonCargarMaterialActionPerformed

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed
             float  totalProduccion =  Float.parseFloat(labelCostoProduccion.getText()), subTotal = 0;
              if(txtCantidadMaterial.getText().length()>0){ //ver que el campo id este lleno
                   if(esEntero(txtCantidadMaterial.getText())){//ver que sea un numero entero 
                       if(Integer.parseInt(txtCantidadMaterial.getText())>0){//ver que la cantidad sea mayor a cero
                           subTotal = Float.parseFloat(labelCosto.getText())*Float.parseFloat(txtCantidadMaterial.getText());
                       totalProduccion = totalProduccion + subTotal;
                       
                       if(tablaMateriales.getRowCount() == 0){ // si la tabla esta vacia se ingresa directamente 
                       insertarEnTabla(txtId.getText(),labelNombre.getText(),labelExistencia.getText(),labelCosto.getText(),txtCantidadMaterial.getText(),""+subTotal);
                       labelCostoProduccion.setText(""+totalProduccion);
                       limpiarPanelMaterial();
                       botonAnadir.setEnabled(false);
                       botonQuitar.setEnabled(true);
                       botonRemover.setEnabled(false);
                       }
                       else{ // si la tabla no esta vacia, se berifica que no este en la tabla 
                           if(!existeEnTabla(txtId.getText(),tablaMateriales)){ // si no existe en la tabla, se agrega el material 
                             
                       insertarEnTabla(txtId.getText(),labelNombre.getText(),labelExistencia.getText(),labelCosto.getText(),txtCantidadMaterial.getText(),""+subTotal);
                       labelCostoProduccion.setText(""+totalProduccion);
                       limpiarPanelMaterial();
                       botonAnadir.setEnabled(false);
                       botonRemover.setEnabled(false);
                               
                           }
                           else{
                               JOptionPane.showMessageDialog(null,"El material ya esta ingresado","Error",JOptionPane.ERROR_MESSAGE);
                           }
                       }
                           
                       }
                       else{
                           JOptionPane.showMessageDialog(null,"La cantidad debe de ser mayor a cero","Advertecia",JOptionPane.WARNING_MESSAGE);
                       }
                      
                   }
                   else{
                       JOptionPane.showMessageDialog(null,"Ingrese solo digitos","Advertencia",JOptionPane.WARNING_MESSAGE);
                   }
               }        
               else{
                   JOptionPane.showMessageDialog(null,"Llene el campo de cantidad","Advertencia",JOptionPane.WARNING_MESSAGE);
               }
    }//GEN-LAST:event_botonAnadirActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        eliminarRegistroTabla(tablaMateriales, modelo,labelCostoPro);
        if(tablaMateriales.getRowCount() == 0){
            botonQuitar.setEnabled(false);
            labelCostoProduccion.setText("0");
        }
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetalleActionPerformed
       int fila = tablaProducto.getSelectedRow();
       String consulta = "select M.id,M.nombre,M.cantidad as exsitencias,M.tipo,M.costo,PM.Cantidad  from producto_has_material PM\n" +
"inner join producto P on P.id = PM.producto_id\n" +
"inner join material M on M.id = PM.material_id where P.id = ";
       if(fila>=0){
           labelNombrePro.setText(String.valueOf(tablaProducto.getValueAt(fila,2)));
           labelIDPro.setText(String.valueOf(tablaProducto.getValueAt(fila,0)));
           txtDescripcionPro.setText(String.valueOf(tablaProducto.getValueAt(fila,1)));
           labelPresioPro.setText(String.valueOf(tablaProducto.getValueAt(fila,3)));
           labelCostoPro.setText(String.valueOf(tablaProducto.getValueAt(fila,4)));
           consulta = consulta+labelIDPro.getText();
           TablaId tabla = new TablaId(tablaMaterialesPro);
           tabla.llenarTable(consulta,"", "", "", "", "", tituloMaterialPro);
           
           labelCantiMateriales.setText(""+tablaMaterialesPro.getRowCount());
           
           botonDetalle.setEnabled(false);
           botonNuevo.setEnabled(false);
           botonEditar.setEnabled(false);
           botonRegresar.setEnabled(false);
           botonReporte.setEnabled(false);
           
           botonRegresar.setEnabled(true);
           
            tabbed.setEnabledAt(2,true);
            tabbed.setEnabledAt(0,false);
            tabbed.setSelectedIndex(2);
           
       }
       else{
           JOptionPane.showMessageDialog(null,"Seleccione un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_botonDetalleActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
       labelNombrePro.setText("");
       labelIDPro.setText("");
       txtDescripcionPro.setText("");
       labelPresioPro.setText("");
       labelCostoPro.setText("");
       labelCantiMateriales.setText("");
       
       limpiarTabla((DefaultTableModel) tablaMaterialesPro.getModel(), tablaMaterialesPro);
       if(this.tipoUsuario == 1){
           botonDetalle.setEnabled(true);
           botonRegresar.setEnabled(false);
           botonNuevo.setEnabled(true);
           botonEditar.setEnabled(true);
           botonRegresar.setEnabled(false);
           botonReporte.setEnabled(true);
       }
          
           
            tabbed.setEnabledAt(2,false);
            tabbed.setEnabledAt(0,true);
            tabbed.setSelectedIndex(0);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonCargarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarEditActionPerformed
        String id,nombre,existencia,costo;
        if(txtIdMaterialEdit.getText().length()>0){
            if(producto.esEntero(txtIdMaterialEdit.getText())){
                if(producto.existeRegistro(txtIdMaterialEdit.getText(),"material","id")){
                    if(!producto.existeRegistro(txtIdMaterialEdit.getText()+" and producto_id="+labelIdProEdit.getText(),"producto_has_material","material_id")){
                    labelNombreMaterial.setText(producto.getDato("id",txtIdMaterialEdit.getText(),"material","nombre"));
                    labelCostoMaterial.setText(producto.getDato("id",txtIdMaterialEdit.getText(),"material","costo"));
                    labelExistenciaMaterial.setText(producto.getDato("id",txtIdMaterialEdit.getText(),"material","cantidad"));
                    
                    botonCargarEdit.setEnabled(false);
                    botonAnadirEditar.setEnabled(true);
                    botonRemoverEdit.setEnabled(true);
                    txtIdMaterialEdit.setEnabled(false);
                    txtCantidadEdit.setEnabled(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Este material ya esta asignado al producto","Advertencia",JOptionPane.WARNING_MESSAGE);
                    }
                  
                }
                else{
                    JOptionPane.showMessageDialog(null,"Este producto no existe","Advertencia",JOptionPane.WARNING_MESSAGE);
                    txtIdMaterialEdit.setText("");
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Ingrese un digito entero","Advertencia",JOptionPane.WARNING_MESSAGE);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Ingese el ID del material","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonCargarEditActionPerformed

    private void botonRemoverEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoverEditActionPerformed
      limpiarPanelMaterialEditar();
      
    }//GEN-LAST:event_botonRemoverEditActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
       
    }//GEN-LAST:event_CantidadActionPerformed

    private void botonAnadirEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirEditarActionPerformed
      String []info =new String[6];
      float total;
        if(txtCantidadEdit.getText().length()>0){
         if(Float.parseFloat(txtCantidadEdit.getText())>0){
            //String id, String nombre, String existencias, String costo, String cantidad,String subTotal
            info[0] = txtIdMaterialEdit.getText();
            info[1]=labelNombreMaterial.getText();
            info[2]=labelExistenciaMaterial.getText();
            info[3]=labelCostoMaterial.getText();
            info[4]=txtCantidadEdit.getText();
            info[5]=labelSubTotalEdit.getText();
            
            if(tablaNuevoMaterial.getRowCount()>0){
                if(!existeEnTabla(txtIdMaterialEdit.getText(), tablaNuevoMaterial)){
                    modelo2.addRow(info);
                    total = Float.parseFloat(labelTotalEdit.getText());
                    total = total + (Float.parseFloat(labelSubTotalEdit.getText())*Float.parseFloat(txtCantidadEdit.getText()));
                    labelTotalEdit.setText(""+total);
                    limpiarPanelMaterialEditar();
                }
                else{
                 JOptionPane.showMessageDialog(null,"El material ya esta en la tabla","Advertencia",JOptionPane.WARNING_MESSAGE);
                }
                
            }
            else{
                    modelo2.addRow(info);
                    total = Float.parseFloat(labelTotalEdit.getText());
                    total = total + (Float.parseFloat(labelSubTotalEdit.getText())*Float.parseFloat(txtCantidadEdit.getText()));
                    labelTotalEdit.setText(""+total);
                    limpiarPanelMaterialEditar();
            }
            
            
            
               
         }
         else{
             JOptionPane.showMessageDialog(null,"La cantidad debe de ser mayor a cero","Advertencia",JOptionPane.WARNING_MESSAGE);
         }
     }
     else{
         JOptionPane.showMessageDialog(null,"Ingrese la cantidad que necesita","Advertencia",JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_botonAnadirEditarActionPerformed

    private void txtCantidadEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadEditKeyReleased
     float total;
        if(txtCantidadEdit.getText().equals("")==false){
            if(producto.esEntero(txtCantidadEdit.getText())){
            total= Float.parseFloat(txtCantidadEdit.getText())*Float.parseFloat(labelCostoMaterial.getText());
            labelSubTotalEdit.setText(total+"");
            }
            else{
                JOptionPane.showMessageDialog(null,"Ingrese solo valores enteros","Advertencia",JOptionPane.WARNING_MESSAGE);
                txtCantidadEdit.setText("");
                labelSubTotalEdit.setText("0");
            }
        }
        else{
            labelSubTotalEdit.setText("0");
        }
    }//GEN-LAST:event_txtCantidadEditKeyReleased

    private void menuItemQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuitarActionPerformed
        eliminarRegistroTabla(tablaNuevoMaterial, modelo2,labelTotalEdit);
        if(tablaNuevoMaterial.getRowCount() == 0){
            labelTotalEdit.setText("0");
        }
    }//GEN-LAST:event_menuItemQuitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cantidad;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonAnadirEditar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton botonCargarEdit;
    private javax.swing.JButton botonCargarMaterial;
    private javax.swing.JButton botonDetalle;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonRemover;
    private javax.swing.JButton botonRemoverEdit;
    private javax.swing.JButton botonReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelCantiMateriales;
    private javax.swing.JLabel labelCosto;
    private javax.swing.JLabel labelCostoMaterial;
    private javax.swing.JLabel labelCostoPro;
    private javax.swing.JLabel labelCostoProEdit;
    private javax.swing.JLabel labelCostoProduccion;
    private javax.swing.JLabel labelExistencia;
    private javax.swing.JLabel labelExistenciaMaterial;
    private javax.swing.JLabel labelIDPro;
    private javax.swing.JLabel labelIdProEdit;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreMaterial;
    private javax.swing.JLabel labelNombrePro;
    private javax.swing.JLabel labelPresioPro;
    private javax.swing.JLabel labelSubTotalEdit;
    private javax.swing.JLabel labelTotalEdit;
    private javax.swing.JMenuItem menuItemQuitar;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tablaMateriales;
    private javax.swing.JTable tablaMaterialesPro;
    private javax.swing.JTable tablaNuevoMaterial;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextArea txtAreaEditar;
    private javax.swing.JTextField txtCantidadEdit;
    private javax.swing.JTextField txtCantidadMaterial;
    private javax.swing.JTextField txtCargar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDescripcionPro;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdMaterialEdit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEditar;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioEditar;
    // End of variables declaration//GEN-END:variables
}
