/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.codehaus.groovy.tools.shell.util.SimpleCompletor;

/**
 *
 * @author Usuario
 */
public class Venta extends javax.swing.JFrame {
    private String localhost = "localhost",puerto = "3305",baseDeDatos = "proyectobd3",usuario ="root",contra = "xela2020", consulta1,nitCli;
    private  String[]  titulo = {"Id","Nombre","Cantidad","Precio","Total"};
    private DefaultTableModel  modeloTabla;
  
    public Venta() {
       
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setTitle("Venta");
        
        modeloTabla = new DefaultTableModel(null,titulo);
        this.tablaProV.setModel(modeloTabla);
        labelFecha.setText(fecha());
        dialogClienteNuevo.setLocationRelativeTo(null);
        dialogClienteNuevo.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        dialogClienteNuevo.setTitle("Nuevo Cliente");
        
        consulta1 = "SELECT M.id,M.cantidad As num_existencias ,PM.Cantidad As contidad_requerida FROM producto_has_material PM\n" +
            "INNER JOIN producto P ON PM.producto_id = P.id\n" +
            "INNER JOIN material M ON PM.material_id = M.id WHERE P.id = ";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogProducto = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtCargar = new javax.swing.JTextField();
        botonCargar = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        botonAgregarPro = new javax.swing.JToggleButton();
        dialogClienteNuevo = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        botonFinalizar = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAbono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelCambio = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JToggleButton();

        dialogProducto.setSize(new java.awt.Dimension(461, 359));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaProducto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonCargar.setText("Cargar");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(botonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCargar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargar))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAgregarPro.setText("Agregar");
        botonAgregarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(botonAgregarPro)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAgregarPro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogProductoLayout = new javax.swing.GroupLayout(dialogProducto.getContentPane());
        dialogProducto.getContentPane().setLayout(dialogProductoLayout);
        dialogProductoLayout.setHorizontalGroup(
            dialogProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogProductoLayout.setVerticalGroup(
            dialogProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogClienteNuevo.setSize(new java.awt.Dimension(450, 349));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Nombre");

        Apellido.setText("Apellido");

        jLabel8.setText("Telefono");

        jLabel9.setText("Correo");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("(Obligatorio)");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("(Obligatorio)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(Apellido)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(txtTelefonoCliente)
                    .addComponent(txtApellidoCliente)
                    .addComponent(txtNombreCliente))
                .addGap(32, 32, 32))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(botonAceptar)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogClienteNuevoLayout = new javax.swing.GroupLayout(dialogClienteNuevo.getContentPane());
        dialogClienteNuevo.getContentPane().setLayout(dialogClienteNuevoLayout);
        dialogClienteNuevoLayout.setHorizontalGroup(
            dialogClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogClienteNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogClienteNuevoLayout.setVerticalGroup(
            dialogClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogClienteNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaProV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProV);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        botonQuitar.setText("Quitar");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCancelar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(botonQuitar)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonFinalizar)
                .addGap(32, 32, 32)
                .addComponent(botonQuitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Total");

        labelFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelFecha.setText("fecha");

        labelTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTotal.setText("0");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("NIT");

        txtAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAbonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAbonoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Abono");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Cambio");

        labelCambio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelCambio.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAbono, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txtNit))
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelFecha)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(labelTotal)
                    .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelCambio))
                .addGap(25, 25, 25))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonBuscar.setText("Buscar Producto");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addGap(130, 130, 130))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonBuscar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String fecha(){
    LocalDate fecha1 = LocalDate.now();
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    return fecha1.format(dtf);
    }
    private void limpiarVentana(){
        labelCambio.setText("0");
        labelTotal.setText("0");
        txtCargar.setText("");
        txtNit.setText("");
        txtAbono.setText("");
    }
    private void limpiarTabla(){
        int filas = tablaProV.getRowCount();
        for(int i=filas-1;i>=0;i--){
            quitarProducto(i);
        }
    }
    private void obtenerTotal(){
        float total = 0;
        int fila = tablaProV.getRowCount();
        if(fila>0){
            
          for(int i = 0; i<fila;i++){
            total = total + Float.parseFloat(String.valueOf(tablaProV.getValueAt(i,4)));   
        }
          
        }
        
        labelTotal.setText(total+"");
    }
    private void cargarTabla(String consulta, String txt, String nombre, String id, String extra, JTable tabla, String[] titulo){
    String campo = txt;
        String where = "";
        if(!"".equals(campo)){
            System.out.println(campo);
            where = "WHERE "+id+ "= "+campo+" OR "+nombre+"= '"+campo+"'";
        }
         try {
         DefaultTableModel modelo = new DefaultTableModel(null,titulo);
         tabla.setModel(modelo);
         ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
         conexion.EjecutarConsulta(consulta+where+" "+extra);
            
            ResultSet rs = conexion.getResulSet();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
              
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int i=0; i <cantidadColumnas ; i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,"Error de conexion","Error",JOptionPane.ERROR_MESSAGE);
         System.out.println(ex.getMessage());
        
    }

}
    private boolean buscarMaterial(int id){
        boolean existe = false;
        
        for(int i = 0; i<tablaProV.getRowCount();i++){
            if(id == Integer.parseInt(String.valueOf(tablaProV.getValueAt(i,0))) ){
                existe = true;
            }
        }
        return existe;
    }
    //insertar en la tabla, productos a vender 
    private void insertarEnTabla(int id, String nombre,int cantidad,float precio,float total ,DefaultTableModel modelo){
        String []info =new String[5];
                        info[0] = Integer.toString(id);
                        info[1] = nombre;
                        info[2] = Integer.toString(cantidad);
                        info[3] = Float.toString(precio);
                        info[4] = Float.toString(total);
                        modelo.addRow(info); 
    }
    private void sumarCantidadMaterial(int idProducto,int cantidad){
       int cantiRequerida, existenciasM, cantidadModificada, idMaterial;
        try {
            ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion.EjecutarConsulta(consulta1+idProducto);
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                cantiRequerida = Integer.parseInt(rs.getString("contidad_requerida"));//cantidad de un producto para hacer cierto material
                existenciasM = Integer.parseInt(rs.getString("num_existencias"));//cantidad del material (lo que tenemos en existencia de ese material)
                idMaterial = Integer.parseInt(rs.getString("M.id"));
                cantidadModificada = existenciasM+(cantiRequerida*cantidad);
                //System.out.println("id material: "+idMaterial+" cantidad para el pedido: "+(cantiRequerida*cantidad)+" Cantidad del Material: "+existenciasM+" Cantidad modificada: "+cantidadModificada);
                editarCantidadMaterial(idMaterial, cantidadModificada);
            } 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        } 
    }
    private void restarCantidadMaterial(int idProducto,int cantidad){
        int cantiRequerida, existenciasM, cantidadModificada, idMaterial;
        try {
            ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion.EjecutarConsulta(consulta1+idProducto);
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                cantiRequerida = Integer.parseInt(rs.getString("contidad_requerida"));//cantidad de un producto para hacer cierto material
                existenciasM = Integer.parseInt(rs.getString("num_existencias"));//cantidad del material (lo que tenemos en existencia de ese material)
                idMaterial = Integer.parseInt(rs.getString("M.id"));
                cantidadModificada = existenciasM-(cantiRequerida*cantidad);
                //System.out.println("id material: "+idMaterial+" cantidad para el pedido: "+(cantiRequerida*cantidad)+" Cantidad del Material: "+existenciasM+" Cantidad modificada: "+cantidadModificada);
                editarCantidadMaterial(idMaterial, cantidadModificada);
            } 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }
    //editar la cantidad del material en la base de datos
    private void editarCantidadMaterial(int idMaterial, int cantidad){
         ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
         conexion.EjecutarInstruccion("UPDATE material SET cantidad = "+ cantidad+" WHERE id = "+idMaterial);
    }
    //Comprobar que el pedido con el producto se puede realizar
    private boolean comprabarExistenciasM(int cantidad,int id){
    boolean existencia = true;
    int cantiRequerida, existenciasM;// cantidad que se requiere para hacer un producto / numero de existencias del material
    try {
            ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion.EjecutarConsulta(consulta1+id);
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                cantiRequerida = Integer.parseInt(rs.getString("contidad_requerida"));//cantidad de un producto para hacer cierto material
                existenciasM = Integer.parseInt(rs.getString("num_existencias"));//cantidad del material (lo que tenemos en existencia de ese material)
                /*
                si la cantidad de un material para hacer un producto multiplicado por la cantidad de productos que se solicitan, 
                es mayor a los productos en existencia, el pedido no podra realizarce
                */
                if(existenciasM<=(cantiRequerida*cantidad)){
                    existencia = false;
                }
                
            }
            
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    return existencia;
}
    private void quitarProducto(int fila){
      modeloTabla.removeRow(fila);
    }
    private void cancelarVenta(){
        int filas = tablaProV.getRowCount(), id,cantidad;
        if(filas>0){
            for(int i=filas-1;i>=0;i--){
                id = Integer.parseInt(String.valueOf(tablaProV.getValueAt(i,0)));
                cantidad = Integer.parseInt(String.valueOf(tablaProV.getValueAt(i,2)));
                quitarProducto(i);
                sumarCantidadMaterial(id, cantidad);
            }
       }
       limpiarVentana();
    }
    private boolean existeCliente(String nit){
        boolean existe = false;
        try {
            ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion.EjecutarConsulta("SELECT COUNT(*) FROM cliente WHERE nit = '"+nit+"'");
            ResultSet rs = conexion.getResulSet();
            rs.next();
            if(rs.getInt(1)>0){
                existe = true;
            }   
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return existe;   
    }
    //nuevo cliente 
    private void nuevoCliente(String nit, String nombre, String apellido, String telefono, String correo){
       ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
       conexion.EjecutarInstruccion("INSERT INTO cliente(nombre, apellido, nit, telefono, correo)\n" +
       "VALUES ('"+nombre+"','"+apellido+"','"+nit+"','"+telefono+"','"+correo+"')");
        
    }
    private String getIdCliente(String nit){//retorna el id del cliente
        String id = "";
       try {
            ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion.EjecutarConsulta("SELECT id FROM cliente WHERE nit = '"+nit+"'");
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                id = rs.getString("id");
            }
            
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return id;
    }
    private String getIdFactura(){//retorna el id de la ultima factura ingresada
        String id = "";
       try {
            ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion.EjecutarConsulta("SELECT MAX(id)As ultimo FROM factura");
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                id = rs.getString("ultimo");
            }
            
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return id;
        
    }
    private String getIdPago(){//retorna el id del ultimo pago
        String id = "";
       try {
            ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            conexion.EjecutarConsulta("SELECT MAX(id)As ultimo FROM pago");
            ResultSet rs = conexion.getResulSet();
            while(rs.next()){
                id = rs.getString("ultimo");
            }
            
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
        return id;
    }
    private void insertarDetalle_Pro(String idFactura,String idProducto, String cantidad, String precio, String total){//hace la relacion entre la factura y cada producto
       ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
       conexion.EjecutarInstruccion("INSERT INTO detalle_pro(cantidad, precio, factura_id, producto_id, total)\n" +
       "VALUES ("+cantidad+","+precio+","+idFactura+","+idProducto+","+total+")");
    }
    
    private void nuevaFactura(float total,String nit,String id_cliente){//ingresa una nueva factura 
        ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
       conexion.EjecutarInstruccion("INSERT INTO factura(fecha,total, nit,cliente_id)\n" +
       "VALUES ('"+fecha()+"',"+total+",'"+nit+"',"+id_cliente+")");
    }
    private void relacionProductoFactura(String idFactura){//va relacionando los productos que tenemos en la tabla con la factura
        int fila = tablaProV.getRowCount();
        for(int i =0; i<fila;i++){  
                                //id_factura            //id_producto                              //cantidad             
            insertarDetalle_Pro(idFactura,String.valueOf(tablaProV.getValueAt(i,0)), String.valueOf(tablaProV.getValueAt(i,2))
                      //precio                                 //total   
                    , String.valueOf(tablaProV.getValueAt(i,3)),String.valueOf(tablaProV.getValueAt(i,0)));
        }
    }
    private void nuevoPago(String id_cliente,float abono){
        ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
       conexion.EjecutarInstruccion("INSERT INTO pago(abono,cliente_id, fecha)\n" +
       "VALUES ("+abono+","+id_cliente+",'"+fecha()+"')");
        
    }
    private void relacionPagoFactura(String id_factura,String id_Pago){
        ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
       conexion.EjecutarInstruccion("INSERT INTO factura_has_pago(factura_id,pago_id)\n" +
       "VALUES ("+id_factura+","+id_Pago+")");
    }
 //buscar producto, es para agregar un producto a la venta.
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        dialogProducto.setVisible(true);
        dialogProducto.setLocationRelativeTo(null);
        dialogProducto.setTitle("Producto");
    }//GEN-LAST:event_botonBuscarActionPerformed
//boton que agrega un producto a la venta 
    private void botonAgregarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProActionPerformed
      int fila = tablaProducto.getSelectedRow(), idProducto;
      String nombre;
      float precio, total;
      if(fila>=0){
          String cantidad = JOptionPane.showInputDialog("Ingrese la cantidad");//obtenemos la cantidad de productos que se van hacer de uno en especifico
          if(cantidad.length()!=0){
              idProducto = Integer.parseInt(String.valueOf(tablaProducto.getValueAt(fila,0)));//obtenemos el id
          nombre = String.valueOf(tablaProducto.getValueAt(fila,1));
          precio = Float.parseFloat(String.valueOf(tablaProducto.getValueAt(fila,3)));
          total = Float.parseFloat(cantidad)*precio;
          if(buscarMaterial(idProducto)){//si ya agrego el producto para vender 
             JOptionPane.showMessageDialog(null,"Ya ingreso el producto","Advertencia",JOptionPane.WARNING_MESSAGE);
          }
          else{
              try {
              int canti = Integer.parseInt(cantidad);
              if(comprabarExistenciasM(canti, idProducto)){//vemos que existan materiales para realiar el producto
                  insertarEnTabla(idProducto,nombre, canti, precio,total, modeloTabla);
                  restarCantidadMaterial(idProducto, canti);
                  obtenerTotal();
              }
              else{
                  JOptionPane.showMessageDialog(null,"No hay materiales para el pedido","Advertencia",JOptionPane.WARNING_MESSAGE);
              }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null,"Ingrese solo digitos","Advertencia",JOptionPane.WARNING_MESSAGE);
          } 
          }
          }
          else{
              JOptionPane.showMessageDialog(null,"Ingrese un digito","Advertencia",JOptionPane.WARNING_MESSAGE);
          }
          
      }
      else{
          JOptionPane.showMessageDialog(null,"Seleccione un producto","Error",JOptionPane.ERROR_MESSAGE);
      }
     
    }//GEN-LAST:event_botonAgregarProActionPerformed
//cargar los productos 
    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
       String[]  titulos = {"Id","Nombre","Descripcion","Precio","Productos a utilizar"};
        String consulta = "SELECT PM.producto_id As id_Producto,P.nombre As nombre_Producto,P.descripcion,P.precio,COUNT(*) Total_Materiales FROM producto_has_material PM\n" +
"INNER JOIN producto P ON PM.producto_id = P.id\n" +
"INNER JOIN material M ON PM.material_id = M.id ";
        cargarTabla(consulta, txtCargar.getText(),"P.nombre","P.id","GROUP BY P.id", tablaProducto, titulos);
    }//GEN-LAST:event_botonCargarActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        int fila = tablaProV.getSelectedRow(), id, cantidad;
        if(fila>=0){
            id = Integer.parseInt(String.valueOf(tablaProV.getValueAt(fila,0)));
            cantidad = Integer.parseInt(String.valueOf(tablaProV.getValueAt(fila,2)));
            quitarProducto(fila);
            sumarCantidadMaterial(id, cantidad);
            obtenerTotal();
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Seleccione un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
        }  
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        int res = JOptionPane.showConfirmDialog(null,"Desea cancelar la venta","Alerta",JOptionPane.YES_NO_OPTION);
        if(res==0){
          cancelarVenta();  
        }
        
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void txtAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonoKeyTyped
        char validar = evt.getKeyChar();
       if(Character.isLetter(validar)){
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(null,"Ingrese solo digitos","Advertencia",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtAbonoKeyTyped

    private void txtAbonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonoKeyReleased
       float cambio;
        if(txtAbono.getText().equals("")==false){
            cambio= Float.parseFloat(txtAbono.getText())-Float.parseFloat(labelTotal.getText());
            labelCambio.setText(cambio+"");
            
        }
        else{
            labelCambio.setText("0.0");
        }
    }//GEN-LAST:event_txtAbonoKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int res = JOptionPane.showConfirmDialog(null,"¿Desea cerrar el modulo de venta?","Alerta", JOptionPane.YES_NO_OPTION);
        if(res == 0){
           cancelarVenta();
            setVisible(false);
            dispose();
            System.exit(0);
       }
    }//GEN-LAST:event_formWindowClosing

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
       int idFactura, IdPago,idCliente;       
       float total, cambio, abono;
        int res = JOptionPane.showConfirmDialog(null,"Desea continuar con la venta","Alerta",JOptionPane.YES_NO_OPTION);
       if(res == 0){
            /*1) */ if((txtNit.getText().length()>0&&tablaProV.getRowCount()>0&&txtAbono.getText().length()>0)){//ver que cada campo este lleno
           
           nitCli = txtNit.getText();
            abono=Float.parseFloat(txtAbono.getText());
            total = Float.parseFloat(labelTotal.getText());
            cambio = Float.parseFloat(labelCambio.getText());
            if(abono >=(total/2)){
                if(!existeCliente(txtNit.getText())){//si el cliente no existe 
                    dialogClienteNuevo.setVisible(true);//nuevo cliente 
            }
                nuevaFactura(total, nitCli,getIdCliente(nitCli));//crear la factura
                System.out.println("nueva factura");
                
                relacionProductoFactura(getIdFactura());//relacionamos los productos con la factura
                System.out.println("relacion producto factura");
                
                nuevoPago(getIdCliente(nitCli),abono);//realizamos el primer pago
                System.out.println("primer pago");
                
                relacionPagoFactura(getIdFactura(),getIdPago());//relacionamos el primer pago con la factura
                System.out.println("relacion primer pago con factura");
                
                limpiarTabla();   
                limpiarVentana();
            }
            else{
                JOptionPane.showMessageDialog(null,"El bono inicial debe de ser mayor o igual al 50% del total");
            }
            
       }
        else{
            JOptionPane.showMessageDialog(null,"Ingrese los datos obligatorios");
        }
       }
      
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(txtNombreCliente.getText().length()>0&&txtApellidoCliente.getText().length()>0){
            nuevoCliente(nitCli,txtNombreCliente.getText(),txtApellidoCliente.getText(),txtTelefonoCliente.getText(),txtCorreoCliente.getText());
        JOptionPane.showMessageDialog(null,"Cliente ingresado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        dialogClienteNuevo.setVisible(false);
        dialogClienteNuevo.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Llene los campos obligatorio","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JToggleButton botonAgregarPro;
    private javax.swing.JToggleButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JToggleButton botonCargar;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JDialog dialogClienteNuevo;
    private javax.swing.JDialog dialogProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tablaProV;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField txtAbono;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtCargar;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
