/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Clases.*;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Compra extends javax.swing.JInternalFrame {

    private String[] titulos = {"Id", "Nombre", "Precio", "Cantidad", "Total"};
    private DefaultTableModel modelo;
    private VariableGlobal conexion;
    private float abono;
    private Bitacoratxt escribir;
    private Date fechaxd;
    public Compra() {

        initComponents();
        conexion = new VariableGlobal();
        generarCodigo();
        txtNombreProveedor.setEnabled(false);
        txtIdProveedor.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtIdMaterial.setEnabled(false);
        txtFecha.setEnabled(false);
        txtExistencias.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtTotal.setEnabled(false);
        txtTotal2.setEnabled(false);
        txtPrimerPago.setEnabled(false);
        txtFecha.setText(fecha());
        escribir = new Bitacoratxt();
        botonAnadir.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonCargarMat.setEnabled(false);
        botonCargarPro.setEnabled(false);
        botonQuitar.setEnabled(false);
        botonCancelar.setEnabled(false);
        botonRemoverMaterial.setEnabled(false);
        botonRemoverProveedor.setEnabled(false);
        modelo = new DefaultTableModel(null, titulos);
        this.tablaMat1.setModel(modelo);

        botonCargarMat.setToolTipText("Cargar Material");
        botonCargarPro.setToolTipText("Cargar Proveedor");
        botonRemoverMaterial.setToolTipText("Remover Material");
        botonRemoverProveedor.setToolTipText("Remover Proveedor");
        botonAnadir.setToolTipText("Añadir");
        botonQuitar.setToolTipText("Quitar");
        botonNuevo.setToolTipText("Nuevo");
        botonGuardar.setToolTipText("Guardar");
        botonCancelar.setToolTipText("Cacelar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        botonCargarPro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        botonRemoverProveedor = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        labelCodigoCompra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTotal2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtIdMaterial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtExistencias = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonCargarMat = new javax.swing.JButton();
        botonRemoverMaterial = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        botonAnadir = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMat1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        txtPrimerPago = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Compra");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Datos Compra"));

        txtIdProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));
        txtIdProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdProveedorKeyTyped(evt);
            }
        });

        jLabel2.setText("ID PROVEEDOR");

        txtFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        botonCargarPro.setBackground(new java.awt.Color(255, 255, 255));
        botonCargarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCargarPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarProMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarProMouseExited(evt);
            }
        });
        botonCargarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarProActionPerformed(evt);
            }
        });

        jLabel3.setText("FECHA");

        txtNombreProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        jLabel11.setText("NOMBRE PROVEEDOR");

        botonRemoverProveedor.setBackground(new java.awt.Color(255, 255, 255));
        botonRemoverProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        botonRemoverProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRemoverProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRemoverProveedorMouseExited(evt);
            }
        });
        botonRemoverProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoverProveedorActionPerformed(evt);
            }
        });

        jLabel13.setText("No. COMPRA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRemoverProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelCodigoCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCargarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodigoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonRemoverProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)));

        botonNuevo.setBackground(new java.awt.Color(255, 255, 255));
        botonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo2.png"))); // NOI18N
        botonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonNuevoMouseExited(evt);
            }
        });
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/guardar2.png"))); // NOI18N
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancelar2.png"))); // NOI18N
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCancelarMouseExited(evt);
            }
        });
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel12.setText("TOTAL");

        txtTotal2.setBackground(new java.awt.Color(0, 0, 0));
        txtTotal2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtTotal2.setForeground(new java.awt.Color(0, 153, 0));
        txtTotal2.setText("0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTotal2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(botonNuevo)
                .addGap(83, 83, 83)
                .addComponent(botonGuardar)
                .addGap(82, 82, 82)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Datos Material"));

        txtIdMaterial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));
        txtIdMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMaterialActionPerformed(evt);
            }
        });
        txtIdMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdMaterialKeyTyped(evt);
            }
        });

        jLabel5.setText("ID DEL MATERIAL");

        jLabel6.setText("NOMBRE");

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        txtExistencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        jLabel7.setText("EXISTENCIAS");

        jLabel8.setText("PRECIO");

        botonCargarMat.setBackground(new java.awt.Color(255, 255, 255));
        botonCargarMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCargarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarMatMouseExited(evt);
            }
        });
        botonCargarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarMatActionPerformed(evt);
            }
        });

        botonRemoverMaterial.setBackground(new java.awt.Color(255, 255, 255));
        botonRemoverMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        botonRemoverMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRemoverMaterialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRemoverMaterialMouseExited(evt);
            }
        });
        botonRemoverMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoverMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdMaterial)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRemoverMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(121, 121, 121)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(txtExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonCargarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRemoverMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)));

        txtCantidad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel9.setText("CANTIDAD");

        jLabel10.setText("TOTAL");

        txtTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        botonAnadir.setBackground(new java.awt.Color(255, 255, 255));
        botonAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/shopping-cart-add_25345 (1).png"))); // NOI18N
        botonAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAnadirMouseExited(evt);
            }
        });
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });

        botonQuitar.setBackground(new java.awt.Color(255, 255, 255));
        botonQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/shopping-cart-remove_25320.png"))); // NOI18N
        botonQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonQuitarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonQuitarMouseExited(evt);
            }
        });
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(txtTotal))
                .addGap(74, 74, 74)
                .addComponent(botonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28))))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)));

        tablaMat1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMat1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)));

        txtPrimerPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        txtPrimerPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrimerPagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrimerPagoKeyTyped(evt);
            }
        });

        jLabel14.setText("PRIMER PAGO ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrimerPago, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPrimerPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String fecha() {
        LocalDate fecha1 = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        return fecha1.format(dtf);
    }
    private String obtenerfecha() {
        fechaxd = new Date();
        DateFormat fechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String convertido = fechaHora.format(fechaxd);
        return convertido;
    }

    private void activarBasico() {
        txtIdMaterial.setEnabled(true);
        txtIdProveedor.setEnabled(true);
        txtPrimerPago.setEnabled(true);

        botonCargarMat.setEnabled(true);
        botonCargarPro.setEnabled(true);
        botonCancelar.setEnabled(true);
        botonGuardar.setEnabled(true);
        botonAnadir.setEnabled(true);
        botonQuitar.setEnabled(true);
        botonRemoverMaterial.setEnabled(true);
        botonRemoverProveedor.setEnabled(true);

        botonNuevo.setEnabled(false);
    }

    private void limpiarPanel() {
        txtCantidad.setEnabled(false);
        txtIdMaterial.setEnabled(false);
        txtIdProveedor.setEnabled(false);
        txtPrimerPago.setEnabled(false);

        txtCantidad.setText("");
        txtIdMaterial.setText("");
        txtIdProveedor.setText("");
        txtNombre.setText("");
        txtTotal.setText("");
        txtPrecio.setText("");
        txtExistencias.setText("");
        txtNombreProveedor.setText("");
        txtPrimerPago.setText("");
        txtTotal2.setText("0.0");

        botonCargarMat.setEnabled(false);
        botonCargarPro.setEnabled(false);
        botonCancelar.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonAnadir.setEnabled(false);
        botonQuitar.setEnabled(false);
        botonRemoverMaterial.setEnabled(false);
        botonRemoverProveedor.setEnabled(false);

        botonNuevo.setEnabled(true);
    }

    private void limpiarTabla(DefaultTableModel modelo, JTable tabla) {
        int fila = tabla.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void generarCodigo() {
        int entero;
        String numero = "";
        String ultimoNum = "";
        try {
            conexion.conexionMySQL.EjecutarConsulta("SELECT MAX(no_factura) FROM compra");
            ResultSet rs = conexion.conexionMySQL.getResulSet();

            if (rs.next()) {
                ultimoNum = rs.getString(1);
            }
            if (ultimoNum == null) {
                labelCodigoCompra.setText("CC0001");
            } else {
                char r1 = ultimoNum.charAt(2);
                char r2 = ultimoNum.charAt(3);
                char r3 = ultimoNum.charAt(4);
                char r4 = ultimoNum.charAt(5);
                String cadena = "";
                cadena = "" + r1 + r2 + r3 + r4;

                entero = Integer.parseInt(cadena);
                Codigo codigo = new Codigo();
                codigo.generarCodigo(entero);
                labelCodigoCompra.setText("CC" + codigo.getCodigo());
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void limpiarAreaMaterial() {
        txtIdMaterial.setEnabled(true);
        txtIdMaterial.setText("");
        txtNombre.setText("");

        txtCantidad.setText("");
        txtCantidad.setEnabled(false);
        txtTotal.setText("");
        txtPrecio.setText("");
        txtExistencias.setText("");
    }

    private boolean esEntero(String id) {
        boolean entero = false;
        try {
            Integer.parseInt(id);
            entero = true;
        } catch (Exception e) {
        }
        return entero;
    }

    private void eliminarRegistroTabla(JTable tabla, DefaultTableModel modelo) {
        int fila = tabla.getSelectedRow();
        float total = Float.parseFloat(txtTotal2.getText()), subTotal;
        if (fila >= 0) {
            subTotal = Float.parseFloat(String.valueOf(tablaMat1.getValueAt(fila, 4)));
            modelo.removeRow(fila);
            total = total - subTotal;
            txtTotal2.setText("" + total);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un material", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void insertarEnTabla(String id, String nombre, String precio, String cantidad, String total) {
        String[] info = new String[5];
        info[0] = id;
        info[1] = nombre;
        info[2] = precio;
        info[3] = cantidad;
        info[4] = total;
        modelo.addRow(info);

    }

    private boolean existeEnTabla(String id) {
        boolean existe = false;
        int iD;
        iD = Integer.parseInt(id);
        for (int i = 0; i < tablaMat1.getRowCount(); i++) {
            if (iD == Integer.parseInt(String.valueOf(tablaMat1.getValueAt(i, 0)))) {
                existe = true;
            }
        }
        return existe;
    }

    private boolean existeRegistro(String parametro, String tabla, String formaParametro) {
        boolean existe = false;

        try {
            conexion.conexionMySQL.EjecutarConsulta("SELECT COUNT(*) FROM " + tabla + " WHERE " + formaParametro + " = " + parametro + "");
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            rs.next();
            if (rs.getInt(1) > 0) {
                existe = true;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return existe;
    }

    private String getDato(String formaId, String id, String tabla, String parametro) {
        String dato = "";

        conexion.conexionMySQL.EjecutarConsulta("SELECT * FROM " + tabla + " WHERE " + formaId + " = " + id);
        ResultSet rs = conexion.conexionMySQL.getResulSet();
        try {
            while (rs.next()) {
                dato = rs.getString(parametro);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dato;
    }

    private boolean esFlotante(String abono) {
        boolean entero = false;
        try {
            Float.parseFloat(abono);
            entero = true;
        } catch (Exception e) {
        }
        return entero;
    }

    private void crearCompra(String fecha, String total, String codigo, String idProveedor) {
        conexion.conexionMySQL.EjecutarInstruccion("insert into compra(fecha,total,no_factura,proveedor_id)\n"
                + "values('" + fecha + "'," + total + ",'" + codigo + "'," + idProveedor + ")");
        escribir.Escribirtxt("Se hizo un INSERT en la tabla compra ", obtenerfecha());
    }

    private void crearDetalleCompra(String precio, String cantidad, String idCompra, String idMaterial) {
        conexion.conexionMySQL.EjecutarInstruccion("insert into detalle_compra(precio,cantidad,compra_id,material_id)\n"
                + "values(" + precio + "," + cantidad + "," + idCompra + "," + idMaterial + ")");
        escribir.Escribirtxt("Se hizo un INSERT en la tabla detalleCompra ", obtenerfecha());

    }

    private void crearCredito_has_compra(String idCompra, String idCredito) {
        conexion.conexionMySQL.EjecutarInstruccion("insert into credito_has_compra(credito_id,compra_id)\n"
                + "values(" + idCredito + "," + idCompra + ")");
        escribir.Escribirtxt("Se hizo un INSERT en la tabla Credito_compra ", obtenerfecha());
        
    }

    private void crearCredito(String abono, String fecha, String idProveedor) {
        conexion.conexionMySQL.EjecutarInstruccion("insert into credito(abono,fecha,proveedor_id)\n"
                + "values(" + abono + ",'" + fecha + "'," + idProveedor + ")");
        escribir.Escribirtxt("Se hizo un Insert en la tabla Credito ", obtenerfecha());
    }

    private String getUltimoIdCompra() {
        String id = "";
        try {
            conexion.conexionMySQL.EjecutarConsulta("SELECT MAX(id)As ultimo FROM compra");
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                id = rs.getString("ultimo");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return id;
    }

    private String getUltimoIdCredito() {
        String id = "";
        try {
            conexion.conexionMySQL.EjecutarConsulta("SELECT MAX(id)As ultimo FROM credito");
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                id = rs.getString("ultimo");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return id;
    }

    private String getCantidadMaterial(String idMaterial) {
        String id = "";
        try {
            conexion.conexionMySQL.EjecutarConsulta("select M.cantidad as cantidad from material M where id = " + idMaterial);
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                id = rs.getString("cantidad");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return id;

    }

    private void relacionMaterialDetalle(String idCompra) {
        int fila = tablaMat1.getRowCount();
        for (int i = 0; i < fila; i++) {
            //id_material                                        //cantidad                                           
            crearDetalleCompra(String.valueOf(tablaMat1.getValueAt(i, 2)), String.valueOf(tablaMat1.getValueAt(i, 3)),
                    //idCompra                                //idMaterial   
                    idCompra, String.valueOf(tablaMat1.getValueAt(i, 0)));
            modificarCantidadMaterial(String.valueOf(tablaMat1.getValueAt(i, 0)), String.valueOf(tablaMat1.getValueAt(i, 3)));
        }

    }

    private void modificarCantidadMaterial(String idMaterial, String cantidad) {
        int cantiIngresar, ultimaCantidad, canti;
        ultimaCantidad = Integer.parseInt(getCantidadMaterial(idMaterial));
        cantiIngresar = Integer.parseInt(cantidad);
        canti = ultimaCantidad + cantiIngresar;

        conexion.conexionMySQL.EjecutarInstruccion("UPDATE material SET cantidad = " + canti + " WHERE id = " + idMaterial);
        escribir.Escribirtxt("Se hizo un UPDATE en la tabla Material ", obtenerfecha());
    }
    private void botonCargarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarProActionPerformed
        if (txtIdProveedor.getText().length() > 0) {
            if (esEntero(txtIdProveedor.getText())) {
                if (existeRegistro(txtIdProveedor.getText(), "proveedor", "id")) {
                    txtNombreProveedor.setText(getDato("id", txtIdProveedor.getText(), "proveedor", "nombre"));
                    txtIdProveedor.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "El proveedor no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese solo valores enteros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llene el campo de texto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonCargarProActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        activarBasico();
        conexion.conexionMySQL.EjecutarInstruccion("START TRANSACTION");
        escribir.Escribirtxt("--INICIO TRANSACCION--",obtenerfecha());
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonCargarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarMatActionPerformed
        if (txtIdMaterial.getText().length() > 0) {
            if (esEntero(txtIdMaterial.getText())) {
                if (existeRegistro(txtIdMaterial.getText(), "material", "id")) {
                    txtNombre.setText(getDato("id", txtIdMaterial.getText(), "material", "nombre"));
                    txtExistencias.setText(getDato("id", txtIdMaterial.getText(), "material", "cantidad"));
                    txtPrecio.setText(getDato("id", txtIdMaterial.getText(), "material", "costo"));

                    txtIdMaterial.setEnabled(false);
                    txtCantidad.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "El material no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese solo valores enteros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llene el campo de texto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonCargarMatActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        int numFilas = tablaMat1.getRowCount();
        limpiarPanel();
        if (numFilas > 0) {
            limpiarTabla(modelo, tablaMat1);
        }
        conexion.conexionMySQL.EjecutarInstruccion("ROLLBACK");
        escribir.Escribirtxt("--TRANSACCION ABORTADA-- ", obtenerfecha());

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void txtIdProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProveedorKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtIdProveedorKeyTyped

    private void txtIdMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMaterialKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtIdMaterialKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        float total;
        if (txtCantidad.getText().equals("") == false) {
            if (esEntero(txtCantidad.getText())) {
                total = Float.parseFloat(txtCantidad.getText()) * Float.parseFloat(txtPrecio.getText());
                txtTotal.setText(total + "");
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese solo valores enteros", "Advertencia", JOptionPane.WARNING_MESSAGE);
                txtCantidad.setText("");
            }
        } else {
            txtTotal.setText("");
        }
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed
        float total = Float.parseFloat(txtTotal2.getText()), subTotal;
        if ((txtNombre.getText().length() > 0 && txtCantidad.getText().length() > 0) && (txtIdMaterial.getText().length() > 0)) {
            if (Float.parseFloat(txtTotal.getText()) > 0) {//ve que el subTotal sea mayor a ceo
                if (tablaMat1.getRowCount() > 0) {//vemos si ya hay algun material en la tabla

                    if (!existeEnTabla(txtIdMaterial.getText())) {//si el material no existe en la tabla lo insertamos 
                        subTotal = Float.parseFloat(txtTotal.getText());
                        insertarEnTabla(txtIdMaterial.getText(), txtNombre.getText(), txtPrecio.getText(), txtCantidad.getText(), txtTotal.getText());
                        
                        total = total + subTotal;
                        txtTotal2.setText("" + total);
                        limpiarAreaMaterial();
                    } else {
                        JOptionPane.showMessageDialog(null, "El material ya esta en la tabla", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
                } else {//si la tabla esta vacia insertamos directamente 
                    subTotal = Float.parseFloat(txtTotal.getText());
                    insertarEnTabla(txtIdMaterial.getText(), txtNombre.getText(), txtPrecio.getText(), txtCantidad.getText(), txtTotal.getText());
                    total = total + subTotal;
                    txtTotal2.setText("" + total);
                    limpiarAreaMaterial();
                }

            } else {
                JOptionPane.showMessageDialog(null, "El total del material debe de ser mayor a cero", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor llene los campos de nombre del material y cantidad", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonAnadirActionPerformed

    private void botonRemoverMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoverMaterialActionPerformed
        limpiarAreaMaterial();
    }//GEN-LAST:event_botonRemoverMaterialActionPerformed

    private void botonRemoverProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoverProveedorActionPerformed
        txtIdProveedor.setEnabled(true);
        txtIdProveedor.setText("");
        txtNombreProveedor.setText("");
    }//GEN-LAST:event_botonRemoverProveedorActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        eliminarRegistroTabla(tablaMat1, modelo);
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        String fecha, total, codigo, iDproveedor, idCompra, idCredito;
        if (tablaMat1.getRowCount() > 0 && txtNombreProveedor.getText().length() > 0 && txtPrimerPago.getText().length() > 0) {//comprobamos que los campos importante esten llenos 
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea completar la compra?", "", JOptionPane.YES_NO_OPTION);//le preguntamos si esta de acuerdo en continuar la compra
            if (respuesta == 0) {
                fecha = fecha();
                total = txtTotal2.getText();
                codigo = labelCodigoCompra.getText();
                iDproveedor = txtIdProveedor.getText();

                crearCompra(fecha, total, codigo, iDproveedor);//  #1  primera fase 
                conexion.conexionMySQL.EjecutarInstruccion("COMMIT");
                escribir.Escribirtxt("--TRANSACCION FINALIZADA--",obtenerfecha());
                idCompra = getUltimoIdCompra();
                relacionMaterialDetalle(idCompra);  //#2   segunda fase relacion material con compra
                crearCredito(txtPrimerPago.getText(), fecha, iDproveedor);//#3  tercera fase crear el primer credito.

                idCredito = getUltimoIdCredito();
                crearCredito_has_compra(idCompra, idCredito);//relacion credito con la compra 
                limpiarPanel();
                limpiarTabla(modelo, tablaMat1);
                JOptionPane.showMessageDialog(null, "Compra realizada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                generarCodigo();
            }

        } else {
            JOptionPane.showMessageDialog(null, "La compra debe de tener un proveedor, un primer pago, y por lo menos un material", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void txtPrimerPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerPagoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtPrimerPagoKeyTyped

    private void txtPrimerPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerPagoKeyReleased
        float total;
        if (txtPrimerPago.getText().equals("") == false) {
            if (!esFlotante(txtPrimerPago.getText())) {
                JOptionPane.showMessageDialog(null, "Ingrese solo digitoss", "Advertencia", JOptionPane.WARNING_MESSAGE);
                txtPrimerPago.setText("");
            }
        } else {
            txtTotal.setText("");
        }
    }//GEN-LAST:event_txtPrimerPagoKeyReleased

    private void txtIdMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMaterialActionPerformed

    }//GEN-LAST:event_txtIdMaterialActionPerformed

    private void botonNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoMouseEntered
        if (botonNuevo.isEnabled()) {
            botonNuevo.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonNuevoMouseEntered

    private void botonNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoMouseExited
        botonNuevo.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonNuevoMouseExited

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
        if (botonGuardar.isEnabled()) {
            botonGuardar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited
        botonGuardar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonGuardarMouseExited

    private void botonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseEntered
        if (botonCancelar.isEnabled()) {
            botonCancelar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCancelarMouseEntered

    private void botonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseExited
        botonCancelar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCancelarMouseExited

    private void botonCargarProMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarProMouseEntered
        if (botonCargarPro.isEnabled()) {
            botonCargarPro.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCargarProMouseEntered

    private void botonCargarProMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarProMouseExited
        botonCargarPro.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCargarProMouseExited

    private void botonRemoverProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverProveedorMouseEntered
        if (botonRemoverProveedor.isEnabled()) {
            botonRemoverProveedor.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonRemoverProveedorMouseEntered

    private void botonRemoverProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverProveedorMouseExited
        botonRemoverProveedor.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonRemoverProveedorMouseExited

    private void botonCargarMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarMatMouseEntered
        if (botonCargarMat.isEnabled()) {
            botonCargarMat.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCargarMatMouseEntered

    private void botonCargarMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarMatMouseExited
        botonCargarMat.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCargarMatMouseExited

    private void botonRemoverMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverMaterialMouseEntered
        if (botonRemoverMaterial.isEnabled()) {
            botonRemoverMaterial.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonRemoverMaterialMouseEntered

    private void botonRemoverMaterialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverMaterialMouseExited
        botonRemoverMaterial.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonRemoverMaterialMouseExited

    private void botonAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMouseEntered
        if (botonAnadir.isEnabled()) {
            botonAnadir.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonAnadirMouseEntered

    private void botonAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMouseExited
        botonAnadir.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonAnadirMouseExited

    private void botonQuitarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonQuitarMouseEntered
        if (botonQuitar.isEnabled()) {
            botonQuitar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonQuitarMouseEntered

    private void botonQuitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonQuitarMouseExited
        botonQuitar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonQuitarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCargarMat;
    private javax.swing.JButton botonCargarPro;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonRemoverMaterial;
    private javax.swing.JButton botonRemoverProveedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodigoCompra;
    private javax.swing.JTable tablaMat1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtExistencias;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdMaterial;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrimerPago;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal2;
    // End of variables declaration//GEN-END:variables
}
