/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import InternalFrame.Deudor2;
import Clases.*;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class deudaHistoria extends javax.swing.JInternalFrame {

    private String[] titulos = {"Id", "Fecha", "Total", "No. Compra", "id Proveedor", "Total Pagos", "Total pagado"},
            titulosMat = {"Id", "Nombre", "Alto", "Ancho", "Cantidad", "Color", "Tipo", "Costo", "Cantidad Comprada"},
            tituloCredito = {"Id", "Pago", "Fecha"};
    private ButtonGroup grupoDeRadio;
    private VariableGlobal conexion;

    public deudaHistoria() {
        initComponents();
        conexion = new VariableGlobal();
        grupoDeRadio = new ButtonGroup();
        grupoDeRadio.add(radioDeuda);
        grupoDeRadio.add(radioSaldo);
        radioSaldo.setSelected(true);

        botonPagar.setEnabled(false);
        botonRegresar.setEnabled(false);

        txtFechaF.setEnabled(false);
        txtFechaI.setEnabled(false);
        botonCragarFecha.setEnabled(false);

        tabbedCompra.setEnabledAt(1, false);

        botonReporte.setToolTipText("Reporte");
        botonDetalle.setToolTipText("Detalle");
        botonRegresar.setToolTipText("Regresar");
        botonPagar.setToolTipText("Pagar");
        botonCargarId.setToolTipText("Cargar ID");
        botonCragarFecha.setToolTipText("Cargar Fecha");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        tabbedCompra = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompra = new javax.swing.JTable();
        botonReporte = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        radioDeuda = new javax.swing.JRadioButton();
        radioSaldo = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        botonCargarId = new javax.swing.JButton();
        comoboCargar = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFechaI = new javax.swing.JTextField();
        txtFechaF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonCragarFecha = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelNumCuenta = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelIdProveedor = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMat = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPago = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        labelSubTotal = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lableIdCompra = new javax.swing.JLabel();
        labelFechaC = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botonDetalle = new javax.swing.JButton();
        botonPagar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        jScrollPane4.setViewportView(jTextPane1);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Deudas / Historia");
        setFrameIcon(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)), "Compras"));

        tablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCompra);

        botonReporte.setBackground(new java.awt.Color(255, 255, 255));
        botonReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte.png"))); // NOI18N
        botonReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReporteMouseExited(evt);
            }
        });
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(botonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)), "Tipo de compra"));

        radioDeuda.setBackground(new java.awt.Color(255, 255, 255));
        radioDeuda.setText("Deudas");
        radioDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDeudaActionPerformed(evt);
            }
        });

        radioSaldo.setBackground(new java.awt.Color(255, 255, 255));
        radioSaldo.setText("Saldados");
        radioSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(radioDeuda)
                .addGap(81, 81, 81)
                .addComponent(radioSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSaldo)
                    .addComponent(radioDeuda))
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)), "Forma de busqueda"));

        botonCargarId.setBackground(new java.awt.Color(255, 255, 255));
        botonCargarId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCargarId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarIdMouseExited(evt);
            }
        });
        botonCargarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarIdActionPerformed(evt);
            }
        });

        comoboCargar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Rango De Fecha" }));
        comoboCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoboCargarActionPerformed(evt);
            }
        });

        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jLabel1.setText("ID / No. COMPRA");

        txtFechaI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        txtFechaF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jLabel2.setText("FECHA INICIO");

        jLabel3.setText("FECHA FINAL");

        botonCragarFecha.setBackground(new java.awt.Color(255, 255, 255));
        botonCragarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCragarFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCragarFechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCragarFechaMouseExited(evt);
            }
        });
        botonCragarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCragarFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCragarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFechaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(txtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(comoboCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(botonCargarId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(235, 235, 235))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comoboCargar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCargarId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCragarFecha)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        tabbedCompra.addTab("Compra", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)), "Proveedor"));

        jLabel10.setText("NOMBRE:");

        jLabel11.setText("TELEFONO:");

        jLabel12.setText("CELULAR:");

        jLabel13.setText("DIRECCION:");

        jLabel14.setText("CORREO:");

        jLabel15.setText("No. CUENTA:");

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombre.setText("nombre");

        labelTelefono.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTelefono.setText("telefono");

        labelDireccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelDireccion.setText("direccion");

        labelNumCuenta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNumCuenta.setText("num");

        labelCelular.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCelular.setText("Celular");

        labelCorreo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCorreo.setText("correo");

        jLabel20.setText("ID PROVEEDOR");

        labelIdProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelIdProveedor.setText("jLabel21");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel20)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(labelIdProveedor)
                    .addComponent(labelTelefono)
                    .addComponent(labelDireccion))
                .addGap(61, 61, 61)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel12))
                    .addComponent(jLabel15))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCelular)
                    .addComponent(labelCorreo)
                    .addComponent(labelNumCuenta))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(labelIdProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelTelefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelDireccion)
                    .addComponent(jLabel14)
                    .addComponent(labelCorreo))
                .addGap(26, 26, 26))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(labelNumCuenta)))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelCelular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Materiales"));

        tablaMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaMat);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Pagos"));

        tablaPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaPago);

        jLabel21.setText("TOTAL DE PAGOS ");

        labelSubTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelSubTotal.setText("jLabel22");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(26, 26, 26)
                .addComponent(labelSubTotal)
                .addGap(74, 74, 74))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(labelSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Compra"));

        jLabel17.setText("ID COMPRA");

        jLabel18.setText("FECHA");

        jLabel19.setText("TOTAL");

        lableIdCompra.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lableIdCompra.setText("jLabel20");

        labelFechaC.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFechaC.setText("jLabel21");

        labelTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTotal.setText("jLabel22");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lableIdCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(labelFechaC)
                .addGap(85, 85, 85)
                .addComponent(jLabel19)
                .addGap(21, 21, 21)
                .addComponent(labelTotal)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(lableIdCompra)
                    .addComponent(labelFechaC)
                    .addComponent(labelTotal))
                .addGap(0, 58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedCompra.addTab("Detalle", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(132, 728));

        botonDetalle.setBackground(new java.awt.Color(255, 255, 255));
        botonDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/detalle2.png"))); // NOI18N
        botonDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDetalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDetalleMouseExited(evt);
            }
        });
        botonDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetalleActionPerformed(evt);
            }
        });

        botonPagar.setBackground(new java.awt.Color(255, 255, 255));
        botonPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pagar.png"))); // NOI18N
        botonPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPagarMouseExited(evt);
            }
        });
        botonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarActionPerformed(evt);
            }
        });

        botonRegresar.setBackground(new java.awt.Color(255, 255, 255));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/regresar2.png"))); // NOI18N
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(botonDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(botonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbedCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String fecha() {
        LocalDate fecha1 = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        return fecha1.format(dtf);
    }

    private void cargarTablaId(String consulta, String parametro, String cadena, String id, String extra, String entrada, JTable tabla, String[] titulo) {
        String campo = parametro;
        String where = "";
        if (!"".equals(campo)) {
            where = entrada + id + "= " + campo + " or " + cadena + "= '" + campo + "'";
        }
        try {
            DefaultTableModel modelo = new DefaultTableModel(null, titulo);
            tabla.setModel(modelo);
            conexion.conexionMySQL.EjecutarConsulta(consulta + where + " " + extra);

            ResultSet rs = conexion.conexionMySQL.getResulSet();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error de conexion", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());

        }
    }

    private void cargarTablaFecha(String consulta, JTable tabla, String[] titulo) {
        try {
            DefaultTableModel modelo = new DefaultTableModel(null, titulo);
            tabla.setModel(modelo);
            conexion.conexionMySQL.EjecutarConsulta(consulta);

            ResultSet rs = conexion.conexionMySQL.getResulSet();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error de conexion", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());

        }

    }

    private void datosProveedor(String idProveedor) {

        conexion.conexionMySQL.EjecutarConsulta("select * from proveedor P  where id = " + idProveedor);
        ResultSet rs = conexion.conexionMySQL.getResulSet();
        try {

            ResultSetMetaData rsMd = rs.getMetaData();
            while (rs.next()) {
                labelNombre.setText(rs.getString("nombre"));
                labelTelefono.setText(rs.getString("telefono"));
                labelCelular.setText(rs.getString("celular"));
                labelDireccion.setText(rs.getString("direccion"));
                labelCorreo.setText(rs.getString("correo"));
                labelNumCuenta.setText(rs.getString("num_cuenta"));
                labelIdProveedor.setText(rs.getString("id"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(deudaHistoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void consultaTablaCredito(String idCompra) {
        String consulta = "select C.id,C.abono,C.fecha from credito_has_compra CC\n"
                + "inner join credito C on CC.credito_id = C.id\n"
                + "inner join compra Con on CC.compra_id = Con.id ";
        cargarTablaId(consulta, idCompra, " Con.no_factura ", " Con.id ", "", " where ", tablaPago, tituloCredito);
    }

    private float sumaPagas(String idCompra) {
        float totalPago = 0;
        try {
            conexion.conexionMySQL.EjecutarConsulta("select sum(C.abono) as totalPagado from credito_has_compra CC\n"
                    + "inner join credito C on CC.credito_id = C.id\n"
                    + "inner join compra Con on CC.compra_id = Con.id where Con.id = " + idCompra);
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                totalPago = Float.parseFloat(rs.getString("totalPagado"));
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return totalPago;
    }

    private boolean esFlotante(String abono) {
        boolean entero = false;
        try {
            Float.parseFloat(abono);
            entero = true;
        } catch (Exception e) {
        }
        return entero;
    }

    private String getUltimoIdCredito() {
        String id = "";
        try {
            conexion.conexionMySQL.EjecutarConsulta("SELECT MAX(id)As ultimo FROM credito");
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                id = rs.getString("ultimo");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return id;
    }

    private void crearCredito_has_compra(String idCompra, String idCredito) {
        conexion.conexionMySQL.EjecutarInstruccion("insert into credito_has_compra(credito_id,compra_id)\n"
                + "values(" + idCredito + "," + idCompra + ")");
    }

    private void crearCredito(String abono, String fecha, String idProveedor) {
        conexion.conexionMySQL.EjecutarInstruccion("insert into credito(abono,fecha,proveedor_id)\n"
                + "values(" + abono + ",'" + fecha + "'," + idProveedor + ")");
    }

    private void radioDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDeudaActionPerformed

    }//GEN-LAST:event_radioDeudaActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        tabbedCompra.setSelectedIndex(0);
        tabbedCompra.setEnabledAt(1, false);
        tabbedCompra.setEnabledAt(0, true);
        botonRegresar.setEnabled(false);
        botonDetalle.setEnabled(true);
        botonPagar.setEnabled(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonCargarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarIdActionPerformed
        String consulta = "", parametro, fechaInicio, fechaFinal, cadena = "", id = "", extra = "", entrada = "";
        if (radioDeuda.isSelected()) {
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n"
                    + "inner join compra C on C.id = CC.compra_id\n"
                    + "inner join credito Cre on Cre.id = CC.credito_id  group by C.id having total>totalPagado";
            entrada = " and ";
        }
        if (radioSaldo.isSelected()) {
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n"
                    + "inner join compra C on C.id = CC.compra_id\n"
                    + "inner join credito Cre on Cre.id = CC.credito_id  group by C.id having total<=totalPagado";
            entrada = " and ";

        }

        cadena = " C.no_factura";
        id = "C.id ";
        cargarTablaId(consulta, txtId.getText(), cadena, id, extra, entrada, tablaCompra, titulos);

    }//GEN-LAST:event_botonCargarIdActionPerformed

    private void radioSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSaldoActionPerformed
        botonPagar.setEnabled(false);
    }//GEN-LAST:event_radioSaldoActionPerformed

    private void comoboCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoboCargarActionPerformed
        if (comoboCargar.getSelectedIndex() == 0) {
            //desactivar modulo cargar por rango de fecha
            botonCragarFecha.setEnabled(false);
            txtFechaF.setText("");
            txtFechaI.setText("");

            txtFechaF.setEnabled(false);
            txtFechaI.setEnabled(false);
            //activar modulo cargar por id o numero
            botonCargarId.setEnabled(true);
            txtId.setEnabled(true);
        } else {
            //desactivar modulo id o numero
            botonCargarId.setEnabled(false);
            txtId.setEnabled(false);
            txtId.setText("");
            //activar boton cargar rango de fecha 
            botonCragarFecha.setEnabled(true);
            txtFechaF.setEnabled(true);
            txtFechaI.setEnabled(true);
        }
    }//GEN-LAST:event_comoboCargarActionPerformed

    private void botonCragarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCragarFechaActionPerformed
        String consulta = "", fechaInicial, fechaFinal;
        fechaFinal = txtFechaF.getText();
        fechaInicial = txtFechaI.getText();
        if (radioDeuda.isSelected()) {
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n"
                    + "inner join compra C on C.id = CC.compra_id\n"
                    + "inner join credito Cre on Cre.id = CC.credito_id  group by C.id  having C.fecha between '" + fechaInicial + "' and '" + fechaFinal + "' and total > totalPagado";
        }
        if (radioSaldo.isSelected()) {
            consulta = "select C.id,C.fecha,C.total as total,C.no_factura,C.proveedor_id, count(Cre.id)numPagos, sum(Cre.abono)totalPagado from credito_has_compra CC\n"
                    + "inner join compra C on C.id = CC.compra_id\n"
                    + "inner join credito Cre on Cre.id = CC.credito_id  group by C.id  having C.fecha between '" + fechaInicial + "' and '" + fechaFinal + "' and total <= totalPagado";
        }
        cargarTablaFecha(consulta, tablaCompra, titulos);
    }//GEN-LAST:event_botonCragarFechaActionPerformed

    private void botonDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetalleActionPerformed
        int fila = tablaCompra.getSelectedRow();
        String idCompra, consulta;
        //ver si es una compra en deuda 
        if (fila >= 0) {
            if (radioDeuda.isSelected()) {
                botonPagar.setEnabled(true);
            }

            //datos especificos de la compra
            idCompra = String.valueOf(tablaCompra.getValueAt(fila, 0));
            lableIdCompra.setText(idCompra);
            labelTotal.setText(String.valueOf(tablaCompra.getValueAt(fila, 2)));
            labelFechaC.setText(String.valueOf(tablaCompra.getValueAt(fila, 1)));

            labelSubTotal.setText("" + sumaPagas(lableIdCompra.getText()));
            //activar el panel de detalle 
            tabbedCompra.setSelectedIndex(1);
            tabbedCompra.setEnabledAt(1, true);
            tabbedCompra.setEnabledAt(0, false);
            botonRegresar.setEnabled(true);
            botonDetalle.setEnabled(false);
            //datos del proveedor de la compra 
            datosProveedor(String.valueOf(tablaCompra.getValueAt(fila, 4)));

            consulta = "select M.id,M.nombre,M.alto,M.ancho,M.cantidad,M.color,M.tipo,M.costo,DC.cantidad as contidad_comprada from detalle_compra DC \n"
                    + "inner join compra C on C.id = DC.compra_id\n"
                    + "inner join material M on M.id = DC.material_id ";
            cargarTablaId(consulta, idCompra, " C.no_factura ", " C.id ", "", " where ", tablaMat, titulosMat);
            consultaTablaCredito(idCompra);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un compra", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonDetalleActionPerformed

    private void botonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarActionPerformed
        float totalCompra = Float.parseFloat(labelTotal.getText());

        String ultimoPagoId;
        String pago = JOptionPane.showInputDialog("Ingrese el pago");
        if (esFlotante(pago)) {
            crearCredito(pago, fecha(), labelIdProveedor.getText()); //crear el pago 
            ultimoPagoId = getUltimoIdCredito();//obtener el ultimo id de pago
            crearCredito_has_compra(lableIdCompra.getText(), ultimoPagoId);//hacer la relacion de pago con la compra 
            if (sumaPagas(lableIdCompra.getText()) >= totalCompra) {//ver si el total de pago es mayor o igual al total de la compra 
                JOptionPane.showMessageDialog(null, "La compra se ha pagado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                botonPagar.setEnabled(false);//se bloque el boton de pago si la suma de los pagos es mayor igual al total de la compra
            }
            consultaTablaCredito(lableIdCompra.getText());//volvemos a cargar la tabla de pagos o credito
            labelSubTotal.setText("" + sumaPagas(lableIdCompra.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "El valor que ingreso no es un digito", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonPagarActionPerformed

    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
        try {

            Connection con = conexion.conexionMySQL.getConexion();
            InputStream archivo = getClass().getResourceAsStream("/Reporte/compras.jrxml");

            JasperDesign dise = JRXmlLoader.load(archivo);
            JasperReport jr = JasperCompileManager.compileReport(dise);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(Deudor2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonReporteActionPerformed

    private void botonDetalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDetalleMouseEntered
        if (botonDetalle.isEnabled()) {
            botonDetalle.setBackground(new Color(255, 102, 51));
        }

    }//GEN-LAST:event_botonDetalleMouseEntered

    private void botonDetalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDetalleMouseExited

        botonDetalle.setBackground(Color.WHITE);

    }//GEN-LAST:event_botonDetalleMouseExited

    private void botonPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPagarMouseEntered
        if (botonPagar.isEnabled()) {
            botonPagar.setBackground(new Color(255, 102, 51));
        }

    }//GEN-LAST:event_botonPagarMouseEntered

    private void botonPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPagarMouseExited

        botonPagar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonPagarMouseExited

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
        if (botonRegresar.isEnabled()) {
            botonRegresar.setBackground(new Color(255, 102, 51));
        }


    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited

        botonRegresar.setBackground(Color.WHITE);

    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteMouseEntered
        if (botonReporte.isEnabled()) {
            botonReporte.setBackground(new Color(255, 102, 51));
        }


    }//GEN-LAST:event_botonReporteMouseEntered

    private void botonReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteMouseExited
        botonReporte.setBackground(Color.WHITE);

    }//GEN-LAST:event_botonReporteMouseExited

    private void botonCargarIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarIdMouseEntered
        if (botonCargarId.isEnabled()) {
            botonCargarId.setBackground(new Color(255, 102, 51));
        }

    }//GEN-LAST:event_botonCargarIdMouseEntered

    private void botonCargarIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarIdMouseExited
        botonCargarId.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCargarIdMouseExited

    private void botonCragarFechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCragarFechaMouseEntered
        if (botonCragarFecha.isEnabled()) {
            botonCragarFecha.setBackground(new Color(255, 102, 51));
        }

    }//GEN-LAST:event_botonCragarFechaMouseEntered

    private void botonCragarFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCragarFechaMouseExited
        botonCragarFecha.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCragarFechaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarId;
    private javax.swing.JButton botonCragarFecha;
    private javax.swing.JButton botonDetalle;
    private javax.swing.JButton botonPagar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonReporte;
    private javax.swing.JComboBox<String> comoboCargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFechaC;
    private javax.swing.JLabel labelIdProveedor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumCuenta;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel lableIdCompra;
    private javax.swing.JRadioButton radioDeuda;
    private javax.swing.JRadioButton radioSaldo;
    private javax.swing.JTabbedPane tabbedCompra;
    private javax.swing.JTable tablaCompra;
    private javax.swing.JTable tablaMat;
    private javax.swing.JTable tablaPago;
    private javax.swing.JTextField txtFechaF;
    private javax.swing.JTextField txtFechaI;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
