/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Clases.*;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
/**
 * ***
 */
public class Deudor2 extends javax.swing.JInternalFrame {

    private ButtonGroup grupoDeRadio;
    private String[] tituloFactura = {"Id", "Total", "Cantidad Pagos", "Total de pagos", "Fecha", "Cliente", "Nit"},
            tituloProducto = {"Id", "Nombre", "Cantidad", "Precio", "Total"},
            tituloPago = {"Id", "Abono", "No.", "Fecha"};
    private Modulo deudor;
    private VariableGlobal conexion;

    public Deudor2() {
        initComponents();
        grupoDeRadio = new ButtonGroup();
        grupoDeRadio.add(radioDeudor);
        grupoDeRadio.add(radioSaldado);
        radioSaldado.setSelected(true);

        tabbed.setEnabledAt(1, false);
        botonDetalle.setEnabled(true);
        botonRegresar.setEnabled(false);
        botonCargarFecha.setEnabled(false);
        botonAbono.setEnabled(false);
        txtFechaInicial.setEnabled(false);
        txtFechaFinal.setEnabled(false);

        deudor = new Modulo();
        conexion = new VariableGlobal();

        botonDetalle.setToolTipText("Detalle");
        botonAbono.setToolTipText("Pago");
        botonRegresar.setToolTipText("Regresar");
        botonCargarFecha.setToolTipText("Cargar Por Rando De Fecha");
        botonCargarNit.setToolTipText("Cargar Por Nit");

        botonReporteFact.setToolTipText("Reporte Facturas");
        botonReportePago.setToolTipText("Reporte Factura");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();
        botonReporteFact = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        radioDeudor = new javax.swing.JRadioButton();
        radioSaldado = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        txtNitCliente = new javax.swing.JTextField();
        botonCargarNit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboTipos = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        txtFechaInicial = new javax.swing.JTextField();
        txtFechaFinal = new javax.swing.JTextField();
        botonCargarFecha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        labelCantidadProducto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPago = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        labelTotalPagos = new javax.swing.JLabel();
        labelCantidadPagos = new javax.swing.JLabel();
        botonReportePago = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelNit = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelNumFactura = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        botonDetalle = new javax.swing.JButton();
        botonAbono = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Deudores");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Facturas"));

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaFactura);

        botonReporteFact.setBackground(new java.awt.Color(255, 255, 255));
        botonReporteFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte.png"))); // NOI18N
        botonReporteFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReporteFactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReporteFactMouseExited(evt);
            }
        });
        botonReporteFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteFactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonReporteFact, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonReporteFact, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Tipo de factura"));

        radioDeudor.setBackground(new java.awt.Color(255, 255, 255));
        radioDeudor.setText("Deudor");

        radioSaldado.setBackground(new java.awt.Color(255, 255, 255));
        radioSaldado.setText("Saldado");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(radioDeudor)
                .addGap(106, 106, 106)
                .addComponent(radioSaldado)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDeudor)
                    .addComponent(radioSaldado))
                .addGap(26, 26, 26))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Forma de busqueda"));

        txtNitCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        botonCargarNit.setBackground(new java.awt.Color(255, 255, 255));
        botonCargarNit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCargarNit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarNitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarNitMouseExited(evt);
            }
        });
        botonCargarNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarNitActionPerformed(evt);
            }
        });

        jLabel1.setText("NIT CLIENTE");

        comboTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nit cliente", "Rango Fecha", " " }));
        comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposActionPerformed(evt);
            }
        });

        txtFechaInicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        txtFechaFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        botonCargarFecha.setBackground(new java.awt.Color(255, 255, 255));
        botonCargarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCargarFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarFechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarFechaMouseExited(evt);
            }
        });
        botonCargarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarFechaActionPerformed(evt);
            }
        });

        jLabel2.setText("FECHA INICIAL");

        jLabel3.setText("FECHA FINAL");

        jLabel31.setText("FORMATO: Anio / Mes/ Dia");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCargarNit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(txtFechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel31))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(txtNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 224, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonCargarNit)))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonCargarFecha))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed.addTab("Factura", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Producto"));

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProducto);

        jLabel27.setText("CANTIDAD:");

        labelCantidadProducto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCantidadProducto.setText("jLabel28");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCantidadProducto)
                .addGap(114, 114, 114))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(labelCantidadProducto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Pago"));

        tablaPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaPago);

        jLabel25.setText("TOTAL PAGOS:");

        jLabel26.setText("CANTIDAD:");

        labelTotalPagos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTotalPagos.setText("jLabel29");

        labelCantidadPagos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCantidadPagos.setText("jLabel30");

        botonReportePago.setBackground(new java.awt.Color(255, 255, 255));
        botonReportePago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte.png"))); // NOI18N
        botonReportePago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReportePagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReportePagoMouseExited(evt);
            }
        });
        botonReportePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportePagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(botonReportePago, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalPagos)
                    .addComponent(labelCantidadPagos))
                .addGap(107, 107, 107))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(labelTotalPagos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(labelCantidadPagos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(botonReportePago, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Cliente"));

        jLabel11.setText("NOMBRE:");

        jLabel12.setText("APELLIDO:");

        jLabel13.setText("NIT:");

        jLabel14.setText("TELEFONO:");

        jLabel15.setText("CORREO:");

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombre.setText("jLabel16");

        labelApellido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelApellido.setText("jLabel17");

        labelNit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNit.setText("jLabel18");

        labelTelefono.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTelefono.setText("jLabel19");

        labelCorreo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCorreo.setText("jLabel20");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelApellido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addGap(69, 69, 69)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTelefono)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCorreo)
                .addGap(64, 64, 64))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(labelNombre)
                    .addComponent(labelNit)
                    .addComponent(labelCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(labelApellido)
                    .addComponent(labelTelefono))
                .addGap(25, 25, 25))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Factura"));

        jLabel21.setText("TOTAL:");

        jLabel22.setText("FECHA:");

        labelTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTotal.setText("jLabel23");

        labelFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFecha.setText("jLabel24");

        jLabel16.setText("No. Factura:");

        labelNumFactura.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNumFactura.setText("jLabel17");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal)
                .addGap(92, 92, 92)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFecha)
                .addGap(29, 29, 29))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(labelTotal)
                    .addComponent(jLabel16)
                    .addComponent(labelNumFactura)
                    .addComponent(jLabel22)
                    .addComponent(labelFecha))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbed.addTab("Detalle", jPanel2);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)));

        botonDetalle.setBackground(new java.awt.Color(255, 255, 255));
        botonDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/detalle2.png"))); // NOI18N
        botonDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDetalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDetalleMouseExited(evt);
            }
        });
        botonDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetalleActionPerformed(evt);
            }
        });

        botonAbono.setBackground(new java.awt.Color(255, 255, 255));
        botonAbono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pagar2.png"))); // NOI18N
        botonAbono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAbonoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAbonoMouseExited(evt);
            }
        });
        botonAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbonoActionPerformed(evt);
            }
        });

        botonRegresar.setBackground(new java.awt.Color(255, 255, 255));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/regresar2.png"))); // NOI18N
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botonAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(botonDetalle)
                .addGap(52, 52, 52)
                .addComponent(botonAbono)
                .addGap(55, 55, 55)
                .addComponent(botonRegresar)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbed)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void generarRecibo() {
        try {
            // ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            Connection con = conexion.conexionMySQL.getConexion();
            InputStream archivo = getClass().getResourceAsStream("/Reporte/reciboPago.jrxml");

            HashMap parametros = new HashMap();
            parametros.put("nit", labelNit.getText());
            parametros.put("nombre", labelNombre.getText());
            parametros.put("apellido", labelApellido.getText());

            JasperDesign dise = JRXmlLoader.load(archivo);
            JasperReport jr = JasperCompileManager.compileReport(dise);
            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, con);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(Deudor2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposActionPerformed
        if (comboTipos.getSelectedIndex() == 0) {
            botonCargarNit.setEnabled(true);
            txtNitCliente.setEnabled(true);

            botonCargarFecha.setEnabled(false);
            txtFechaInicial.setEnabled(false);
            txtFechaInicial.setText("");
            txtFechaFinal.setEnabled(false);
            txtFechaFinal.setText("");
        } else {
            botonCargarNit.setEnabled(false);
            txtNitCliente.setEnabled(false);
            txtNitCliente.setText("");

            botonCargarFecha.setEnabled(true);
            txtFechaInicial.setEnabled(true);
            txtFechaFinal.setEnabled(true);
        }
    }//GEN-LAST:event_comboTiposActionPerformed

    private void botonCargarNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarNitActionPerformed
        String consulta = "", condicion = "";
        TablaId tabla = new TablaId(tablaFactura);
        if (radioSaldado.isSelected()) {
            consulta = "select F.id,F.total,count(P.id) as Pagos,sum(P.abono)TotalPagos,F.fecha,C.nombre as cliente,C.nit as nit_cliente  from  factura_has_pago FP\n"
                    + " inner join factura F on FP.factura_id = F.id\n"
                    + " inner join pago P on FP.pago_id = P.id \n"
                    + " inner join cliente C on F.cliente_id = C.id\n"
                    + " group by F.id having F.total<=TotalPagos ";

        }
        if (radioDeudor.isSelected()) {//si es deudor
            consulta = "select F.id,F.total,count(P.id) as Pagos,sum(P.abono)TotalPagos,F.fecha,C.nombre as cliente,C.nit as nit_cliente  from  factura_has_pago FP\n"
                    + " inner join factura F on FP.factura_id = F.id\n"
                    + " inner join pago P on FP.pago_id = P.id \n"
                    + " inner join cliente C on F.cliente_id = C.id\n"
                    + " group by F.id having F.total>TotalPagos ";
        }
        if (txtNitCliente.getText().length() > 0) {//si hay un numero de nit en especifico 
            condicion = "and C.nit = '" + txtNitCliente.getText() + "'";
        }
        tabla.llenarTable(consulta, "", "", "", condicion, consulta, tituloFactura);
        tablaFactura = tabla.getTabla();


    }//GEN-LAST:event_botonCargarNitActionPerformed

    private void botonCargarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarFechaActionPerformed
        String consulta = "", condicion = "";
        TablaId tabla = new TablaId(tablaFactura);
        if (radioSaldado.isSelected()) {
            consulta = "select F.id,F.total,count(P.id) as Pagos,sum(P.abono)TotalPagos,F.fecha,C.nombre as cliente,C.nit as nit_cliente  from  factura_has_pago FP\n"
                    + " inner join factura F on FP.factura_id = F.id\n"
                    + " inner join pago P on FP.pago_id = P.id \n"
                    + " inner join cliente C on F.cliente_id = C.id\n"
                    + " group by F.id having F.total<=TotalPagos ";

        }
        if (radioDeudor.isSelected()) {
            consulta = "select F.id,F.total,count(P.id) as Pagos,sum(P.abono)TotalPagos,F.fecha,C.nombre as cliente,C.nit as nit_cliente  from  factura_has_pago FP\n"
                    + " inner join factura F on FP.factura_id = F.id\n"
                    + " inner join pago P on FP.pago_id = P.id \n"
                    + " inner join cliente C on F.cliente_id = C.id\n"
                    + " group by F.id having F.total>TotalPagos ";
        }
        if (txtFechaInicial.getText().length() > 0 && txtFechaFinal.getText().length() > 0) {
            condicion = "and F.fecha between '" + txtFechaInicial.getText() + "' and '" + txtFechaFinal.getText() + "'";
        }
        tabla.llenarTable(consulta, "", "", "", condicion, "", tituloFactura);
        tablaFactura = tabla.getTabla();
    }//GEN-LAST:event_botonCargarFechaActionPerformed

    private void botonDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetalleActionPerformed
        int fila = tablaFactura.getSelectedRow();
        TablaId tablaPro = new TablaId(tablaProducto);
        TablaId tablaPago1 = new TablaId(tablaPago);
        String consulta;
        if (fila >= 0) {
            //datos del cliente 
            labelNombre.setText(deudor.getDato("nit", "'" + String.valueOf(tablaFactura.getValueAt(fila, 6)) + "'", "cliente", "nombre"));
            labelApellido.setText(deudor.getDato("nit", "'" + String.valueOf(tablaFactura.getValueAt(fila, 6)) + "'", "cliente", "apellido"));
            labelTelefono.setText(deudor.getDato("nit", "'" + String.valueOf(tablaFactura.getValueAt(fila, 6)) + "'", "cliente", "telefono"));
            labelCorreo.setText(deudor.getDato("nit", "'" + String.valueOf(tablaFactura.getValueAt(fila, 6)) + "'", "cliente", "correo"));
            labelNit.setText(String.valueOf(tablaFactura.getValueAt(fila, 6)));
            //datos de la factura 
            labelTotal.setText(String.valueOf(tablaFactura.getValueAt(fila, 1)));
            labelFecha.setText(String.valueOf(tablaFactura.getValueAt(fila, 4)));
            labelNumFactura.setText(deudor.getDato("id", String.valueOf(tablaFactura.getValueAt(fila, 0)), "factura", "numFactura"));
            //llenar tabla producto.
            consulta = " select  P.id,P.nombre,DP.cantidad,DP.precio,DP.total from  detalle_pro DP\n"
                    + " inner join factura F on DP.factura_id = F.id\n"
                    + " inner join producto P on DP.producto_id = P.id \n"
                    + " inner join cliente C on F.cliente_id = C.id\n"
                    + " where  F.id = " + String.valueOf(tablaFactura.getValueAt(fila, 0));
            tablaPro.llenarTable(consulta, "", "", "", "", "", tituloProducto);
            labelCantidadProducto.setText(tablaProducto.getRowCount() + "");
            //llenar tabla pagos.
            consulta = "select P.id,P.abono,P.numPago,P.fecha from factura_has_pago FP\n"
                    + " inner join factura F on FP.factura_id = F.id\n"
                    + " inner join pago P on FP.pago_id = P.id where F.id = " + String.valueOf(tablaFactura.getValueAt(fila, 0));
            tablaPago1.llenarTable(consulta, "", "", "", "", "", tituloPago);
            labelTotalPagos.setText("" + tablaPago1.sumaFlotanteColumna(1));
            labelCantidadPagos.setText(tablaPago.getRowCount() + "");

            //moverse al panel de detalle 
            tabbed.setSelectedIndex(1);
            tabbed.setEnabledAt(1, true);
            tabbed.setEnabledAt(0, false);
            botonRegresar.setEnabled(true);
            botonDetalle.setEnabled(false);
            if (Float.parseFloat(labelTotal.getText()) > Float.parseFloat(labelTotalPagos.getText())) {
                botonAbono.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una factura", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonDetalleActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        tabbed.setSelectedIndex(0);
        tabbed.setEnabledAt(0, true);
        tabbed.setEnabledAt(1, false);
        botonRegresar.setEnabled(false);
        botonDetalle.setEnabled(true);
        botonAbono.setEnabled(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbonoActionPerformed
        String cantiCadena, idCliente, idFactura, columnas, datos, idPago, consulta;
        TablaId tablaPago1 = new TablaId(tablaPago);
        cantiCadena = JOptionPane.showInputDialog("Ingrese el pago");
        if (cantiCadena != null) {
            if (deudor.esFlotante(cantiCadena)) {
                if (Float.parseFloat(cantiCadena) > 0) {
                    //obtener id de cliente y de factura 
                    idCliente = deudor.getDato("nit", "'" + labelNit.getText() + "'", "cliente", "id");
                    System.out.println(idCliente);
                    idFactura = deudor.getDato("numFactura", "'" + labelNumFactura.getText() + "'", "factura", "id");
                    System.out.println(idFactura);
                    //realizar el pago que esta relacionado con el cliente 
                    columnas = "abono,cliente_id,numPago,fecha";
                    datos = cantiCadena + "," + idCliente + ",'" + deudor.generarCodigo("numPago", "pago", "PD") + "','" + deudor.fecha() + "'";
                    deudor.nuevoRegistro(columnas, datos, "pago");

                    //obtener el ultimo id de pago
                    idPago = deudor.getUltimoId("id", "pago");
                    System.out.println(idPago);

                    //relacionar el ultimo pago con la factura
                    columnas = "factura_id,pago_id";
                    datos = idFactura + "," + idPago;
                    deudor.nuevoRegistro(columnas, datos, "factura_has_pago");

                    //consulta a los pagos de la factura, para actualizar
                    consulta = "select P.id,P.abono,P.numPago,P.fecha from factura_has_pago FP\n"
                            + " inner join factura F on FP.factura_id = F.id\n"
                            + " inner join pago P on FP.pago_id = P.id where F.id = " + idFactura;
                    tablaPago1.llenarTable(consulta, "", "", "", "", "", tituloPago);
                    //obtener el recibo de pago
                    generarRecibo();
                    //actualizar el label donde esta el total o suma de los pagos 
                    labelTotalPagos.setText("" + tablaPago1.sumaFlotanteColumna(1));
                    labelCantidadPagos.setText("" + tablaPago.getRowCount());
                    if (tablaPago1.sumaFlotanteColumna(1) >= Float.parseFloat(labelTotal.getText())) {//si el total de los pagos es mayor igual al total de la factura el boton de abono se bloquea
                        botonAbono.setEnabled(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El pago debe de ser mayor a cero", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Solo ingrese digitos", "Adverttencia", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_botonAbonoActionPerformed

    private void botonReporteFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteFactActionPerformed
        if (radioDeudor.isSelected()) {
            try {
                //ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
                Connection con = conexion.conexionMySQL.getConexion();
                InputStream archivo = getClass().getResourceAsStream("/Reporte/deudoresVenta.jrxml");
                JasperDesign dise = JRXmlLoader.load(archivo);
                JasperReport jr = JasperCompileManager.compileReport(dise);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp, false);
            } catch (JRException ex) {
                Logger.getLogger(Deudor2.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                //ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
                Connection con = conexion.conexionMySQL.getConexion();
                InputStream archivo = getClass().getResourceAsStream("/Reporte/deudoresVenta2.jrxml");
                JasperDesign dise = JRXmlLoader.load(archivo);
                JasperReport jr = JasperCompileManager.compileReport(dise);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp, false);
            } catch (JRException ex) {
                Logger.getLogger(Deudor2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_botonReporteFactActionPerformed

    private void botonReportePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportePagoActionPerformed
        try {
            //ConexionMySQL conexion = new ConexionMySQL(localhost,puerto,baseDeDatos,usuario,contra);
            Connection con = conexion.conexionMySQL.getConexion();
            InputStream archivo = getClass().getResourceAsStream("/Reporte/factura.jrxml");

            HashMap parametros = new HashMap();
            parametros.put("id", labelNumFactura.getText());
            parametros.put("idpago", labelNumFactura.getText());
            parametros.put("nit", labelNit.getText());
            parametros.put("nombre", labelNombre.getText());
            parametros.put("apellido", labelApellido.getText());
            parametros.put("numFactura", labelNumFactura.getText());
            parametros.put("total", labelTotal.getText());

            JasperDesign dise = JRXmlLoader.load(archivo);
            JasperReport jr = JasperCompileManager.compileReport(dise);
            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, con);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(Deudor2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonReportePagoActionPerformed

    private void botonDetalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDetalleMouseEntered
        if (botonDetalle.isEnabled()) {
            botonDetalle.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonDetalleMouseEntered

    private void botonDetalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDetalleMouseExited
        botonDetalle.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonDetalleMouseExited

    private void botonAbonoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbonoMouseEntered
        if (botonAbono.isEnabled()) {
            botonAbono.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonAbonoMouseEntered

    private void botonAbonoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbonoMouseExited
        botonAbono.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonAbonoMouseExited

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
        if (botonRegresar.isEnabled()) {
            botonRegresar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
        botonRegresar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonCargarNitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarNitMouseEntered
        if (botonCargarNit.isEnabled()) {
            botonCargarNit.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCargarNitMouseEntered

    private void botonCargarNitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarNitMouseExited
        botonCargarNit.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCargarNitMouseExited

    private void botonCargarFechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarFechaMouseEntered
        if (botonCargarFecha.isEnabled()) {
            botonCargarFecha.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCargarFechaMouseEntered

    private void botonCargarFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarFechaMouseExited
        botonCargarFecha.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCargarFechaMouseExited

    private void botonReporteFactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteFactMouseEntered
        if (botonReporteFact.isEnabled()) {
            botonReporteFact.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonReporteFactMouseEntered

    private void botonReporteFactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteFactMouseExited
        botonReporteFact.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonReporteFactMouseExited

    private void botonReportePagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportePagoMouseEntered
        if (botonReportePago.isEnabled()) {
            botonReportePago.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonReportePagoMouseEntered

    private void botonReportePagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportePagoMouseExited
        botonReportePago.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonReportePagoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbono;
    private javax.swing.JButton botonCargarFecha;
    private javax.swing.JButton botonCargarNit;
    private javax.swing.JButton botonDetalle;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonReporteFact;
    private javax.swing.JButton botonReportePago;
    private javax.swing.JComboBox<String> comboTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCantidadPagos;
    private javax.swing.JLabel labelCantidadProducto;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNit;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumFactura;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalPagos;
    private javax.swing.JRadioButton radioDeudor;
    private javax.swing.JRadioButton radioSaldado;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tablaFactura;
    private javax.swing.JTable tablaPago;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicial;
    private javax.swing.JTextField txtNitCliente;
    // End of variables declaration//GEN-END:variables
}
