/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Clases.Bitacoratxt;
import Clases.Modulo;
import Clases.ConexionMySQL;
import Clases.VariableGlobal;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class Venta2 extends javax.swing.JInternalFrame {

    private String consultaMaterial;
    private String[] titulos = {"Id", "Nombre", "Precio", "Cantidad", "Total"}, datosInsertar;
    private DefaultTableModel modelo;
    private Modulo venta;
    private VariableGlobal conexion;
    private Date fecha;
    private Bitacoratxt escribir;

    public Venta2() {
        initComponents();
        venta = new Modulo();
        conexion = new VariableGlobal();

        labelNo.setText(venta.generarCodigo("numFactura", "factura", "CD"));
        labelFecha.setText(venta.fecha());

        botonAnadir.setEnabled(false);
        botonCancelar.setEnabled(false);
        botonCargarClie.setEnabled(false);
        botonCargarPro.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonQuitar.setEnabled(false);
        botonRemoverClie.setEnabled(false);
        botonRemoverPro.setEnabled(false);
        escribir = new Bitacoratxt();
        txtAreaDescripcion.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtIDproducto.setEnabled(false);
        txtNit.setEnabled(false);

        labelApellido.setText("");
        labelNombreClie.setText("");
        labelNombrePro.setText("");
        labelPrecio.setText("");
        labelId.setText("");
        labelPrecio.setText("");
        labelSubTotal.setText("");
        labelTotal.setText("");
        // labelFecha.setText(fecha());

        modelo = new DefaultTableModel(null, titulos);
        this.tablaProducto.setModel(modelo);

        consultaMaterial = "SELECT M.id,M.cantidad As num_existencias ,PM.Cantidad As contidad_requerida FROM producto_has_material PM\n"
                + "INNER JOIN producto P ON PM.producto_id = P.id\n"
                + "INNER JOIN material M ON PM.material_id = M.id WHERE P.id = ";

        botonAnadir.setToolTipText("Añadir");
        botonQuitar.setToolTipText("Quita");
        botonCargarClie.setToolTipText("Cargar Cliente");
        botonCargarPro.setToolTipText("Cargar Producto");
        botonRemoverClie.setToolTipText("RemoverCliente");
        botonRemoverPro.setToolTipText("Remover Producto");
        botonCerrar.setToolTipText("Cerrar");
        botonNuevo.setToolTipText("Nuevo");
        botonGuardar.setToolTipText("Guardar");
        botonCancelar.setToolTipText("Cancelar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelSubTotal = new javax.swing.JLabel();
        botonAnadir = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtIDproducto = new javax.swing.JTextField();
        botonCargarPro = new javax.swing.JButton();
        botonRemoverPro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        labelPrecio = new javax.swing.JLabel();
        labelNombrePro = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonCargarClie = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNombreClie = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        botonRemoverClie = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        botonNuevo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelNo = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setIconifiable(true);
        setResizable(true);
        setTitle("Venta");
        setPreferredSize(new java.awt.Dimension(725, 880));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProducto);

        jLabel20.setText("TOTAL:");

        labelTotal.setBackground(new java.awt.Color(0, 0, 0));
        labelTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTotal.setText("jLabel19");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(labelTotal)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(labelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)));

        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel14.setText("CANTIDAD:");

        jLabel15.setText("SUBTOTAL:");

        labelSubTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelSubTotal.setText("jLabel16");

        botonAnadir.setBackground(new java.awt.Color(255, 255, 255));
        botonAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/shopping-cart-add_25345 (1).png"))); // NOI18N
        botonAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAnadirMouseExited(evt);
            }
        });
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });

        botonQuitar.setBackground(new java.awt.Color(255, 255, 255));
        botonQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/shopping-cart-remove_25320.png"))); // NOI18N
        botonQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonQuitarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonQuitarMouseExited(evt);
            }
        });
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSubTotal))
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(labelSubTotal)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Producto"));

        txtIDproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));

        botonCargarPro.setBackground(new java.awt.Color(255, 255, 255));
        botonCargarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCargarPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarProMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarProMouseExited(evt);
            }
        });
        botonCargarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarProActionPerformed(evt);
            }
        });

        botonRemoverPro.setBackground(new java.awt.Color(255, 255, 255));
        botonRemoverPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        botonRemoverPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRemoverProMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRemoverProMouseExited(evt);
            }
        });
        botonRemoverPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoverProActionPerformed(evt);
            }
        });

        jLabel10.setText("ID PRODUCTO:");

        jLabel11.setText("NOMBRE:");

        jLabel12.setText("PRECIO:");

        jLabel13.setText("DESCRIPCION:");

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtAreaDescripcion);

        labelPrecio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelPrecio.setText("jLabel17");

        labelNombrePro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombrePro.setText("jLabel18");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(botonCargarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(239, 239, 239)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombrePro)
                            .addComponent(labelPrecio))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRemoverPro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRemoverPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(labelNombrePro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonCargarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Cliente"));

        txtNit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));

        jLabel3.setText("NIT:");

        botonCargarClie.setBackground(new java.awt.Color(255, 255, 255));
        botonCargarClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cargar2.png"))); // NOI18N
        botonCargarClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarClieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarClieMouseExited(evt);
            }
        });
        botonCargarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarClieActionPerformed(evt);
            }
        });

        jLabel4.setText("NOMBRE:");

        jLabel5.setText("APELLIDO:");

        jLabel6.setText("ID:");

        labelNombreClie.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombreClie.setText("jLabel7");

        labelApellido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelApellido.setText("jLabel8");

        labelId.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelId.setText("jLabel9");

        botonRemoverClie.setBackground(new java.awt.Color(255, 255, 255));
        botonRemoverClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        botonRemoverClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRemoverClieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRemoverClieMouseExited(evt);
            }
        });
        botonRemoverClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoverClieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(botonCargarClie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRemoverClie, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelApellido)
                    .addComponent(labelNombreClie)
                    .addComponent(labelId))
                .addGap(48, 48, 48))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelNombreClie))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(labelId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelApellido)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCargarClie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(botonRemoverClie, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        botonNuevo.setBackground(new java.awt.Color(255, 255, 255));
        botonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/new-file_40454 (1).png"))); // NOI18N
        botonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonNuevoMouseExited(evt);
            }
        });
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete_27010.png"))); // NOI18N
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCancelarMouseExited(evt);
            }
        });
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Save_37110 (1).png"))); // NOI18N
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Close_2_26986.png"))); // NOI18N
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrarMouseExited(evt);
            }
        });
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(botonGuardar)
                .addGap(27, 27, 27)
                .addComponent(botonCancelar)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 2));

        jLabel7.setText("No. Factura:");

        jLabel8.setText("FECHA:");

        labelNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNo.setText("jLabel9");

        labelFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFecha.setText("jLabel16");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNo)
                .addGap(169, 169, 169)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFecha)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(labelNo)
                    .addComponent(labelFecha))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarModuloProducto() {
        botonCargarPro.setEnabled(true);
        botonRemoverPro.setEnabled(false);
        txtIDproducto.setEnabled(true);
        txtIDproducto.setText("");

        labelNombrePro.setText("");
        labelPrecio.setText("");
        labelSubTotal.setText("");
        txtAreaDescripcion.setText("");
        botonAnadir.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtCantidad.setText("");
    }

    private String obtenerfecha() {
        fecha = new Date();
        DateFormat fechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String convertido = fechaHora.format(fecha);
        return convertido;
    }

    private void limpiarModuloCliente() {
        txtNit.setEnabled(false);
        txtNit.setText("");

        labelApellido.setText("");
        labelNombreClie.setText("");
        labelId.setText("");

        botonCargarClie.setEnabled(false);
        botonRemoverClie.setEnabled(false);
    }

    private void sumarCantidadMaterial(String idProducto, int cantidad) {
        int cantiRequerida, existenciasM, cantidadModificada, idMaterial;
        try {

            conexion.conexionMySQL.EjecutarConsulta(consultaMaterial + idProducto);
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                cantiRequerida = Integer.parseInt(rs.getString("contidad_requerida"));//cantidad de un producto para hacer cierto material
                existenciasM = Integer.parseInt(rs.getString("num_existencias"));//cantidad del material (lo que tenemos en existencia de ese material)
                idMaterial = Integer.parseInt(rs.getString("M.id"));
                cantidadModificada = existenciasM + (cantiRequerida * cantidad);
                //System.out.println("id material: "+idMaterial+" cantidad para el pedido: "+(cantiRequerida*cantidad)+" Cantidad del Material: "+existenciasM+" Cantidad modificada: "+cantidadModificada);
                editarCantidadMaterial(idMaterial, cantidadModificada);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void restarCantidadMaterial(String idProducto, int cantidad) {
        int cantiRequerida, existenciasM, cantidadModificada, idMaterial;
        try {

            conexion.conexionMySQL.EjecutarConsulta(consultaMaterial + idProducto);
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                cantiRequerida = Integer.parseInt(rs.getString("contidad_requerida"));//cantidad de un producto para hacer cierto material
                existenciasM = Integer.parseInt(rs.getString("num_existencias"));//cantidad del material (lo que tenemos en existencia de ese material)
                idMaterial = Integer.parseInt(rs.getString("M.id"));
                cantidadModificada = existenciasM - (cantiRequerida * cantidad);
                //System.out.println("id material: "+idMaterial+" cantidad para el pedido: "+(cantiRequerida*cantidad)+" Cantidad del Material: "+existenciasM+" Cantidad modificada: "+cantidadModificada);
                editarCantidadMaterial(idMaterial, cantidadModificada);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
//editar la cantidad del material en la base de datos

    private void editarCantidadMaterial(int idMaterial, int cantidad) {
        conexion.conexionMySQL.EjecutarInstruccion("UPDATE material SET cantidad = " + cantidad + " WHERE id = " + idMaterial);
        escribir.Escribirtxt("Se hizo un UPDATE en la tabla Material ", obtenerfecha());
    }

//Comprobar que el pedido con el producto se puede realizar
    private boolean comprabarExistenciasM(int cantidad, String id) {
        boolean existencia = true;
        int cantiRequerida, existenciasM;// cantidad que se requiere para hacer un producto / numero de existencias del material
        try {
            conexion.conexionMySQL.EjecutarConsulta(consultaMaterial + id);
            ResultSet rs = conexion.conexionMySQL.getResulSet();
            while (rs.next()) {
                cantiRequerida = Integer.parseInt(rs.getString("contidad_requerida"));//cantidad de un producto para hacer cierto material

                existenciasM = Integer.parseInt(rs.getString("num_existencias"));//cantidad del material (lo que tenemos en existencia de ese material)
                // System.out.println("cantidad requerida: "+cantiRequerida+" Cantidad para el pedido: "+(cantiRequerida*cantidad)+" cantidad existencia: "+existenciasM);
                /*
                si la cantidad de un material para hacer un producto multiplicado por la cantidad de productos que se solicitan, 
                es mayor a los productos en existencia, el pedido no podra realizarce
                 */
                if (existenciasM < (cantiRequerida * cantidad)) {
                    existencia = false;
                }

            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return existencia;
    }

    private void obtenerTotal(int columna) {
        float total = 0;
        int fila = tablaProducto.getRowCount();
        if (fila > 0) {

            for (int i = 0; i < fila; i++) {
                total = total + Float.parseFloat(String.valueOf(tablaProducto.getValueAt(i, columna)));
            }

        }

        labelTotal.setText(total + "");
    }

    private void cancelarVenta() {
        int filas = tablaProducto.getRowCount(), id, cantidad;
        if (filas > 0) {
            for (int i = filas - 1; i >= 0; i--) {

                cantidad = Integer.parseInt(String.valueOf(tablaProducto.getValueAt(i, 3)));
                sumarCantidadMaterial(String.valueOf(tablaProducto.getValueAt(i, 0)), cantidad);
                venta.quitarFila(i, modelo);
            }
        }

    }

    private void relacionProductoFactura(String idFactura) {//va relacionando los productos que tenemos en la tabla con la factura
        int fila = tablaProducto.getRowCount();
        String datos, columnas;
        columnas = "cantidad,precio,factura_id,producto_id,total";
        for (int i = 0; i < fila; i++) {
            datos = String.valueOf(tablaProducto.getValueAt(i, 3)) + ","
                    + String.valueOf(tablaProducto.getValueAt(i, 2)) + "," + idFactura + "," + String.valueOf(tablaProducto.getValueAt(i, 0)) + "," + String.valueOf(tablaProducto.getValueAt(i, 4));
            venta.nuevoRegistro(columnas, datos, "detalle_pro");
        }
    }

    private void cancelar() {
        cancelarVenta();
        limpiarModuloProducto();
        limpiarModuloCliente();

        botonNuevo.setEnabled(true);
        txtIDproducto.setEnabled(false);
        botonCargarPro.setEnabled(false);

        botonGuardar.setEnabled(false);
        botonCancelar.setEnabled(false);
        botonQuitar.setEnabled(false);
        labelTotal.setText("");
    }

    private void generarFactura() {
        try {

            Connection con = conexion.conexionMySQL.getConexion();
            InputStream archivo = getClass().getResourceAsStream("/Reporte/factura.jrxml");

            HashMap parametros = new HashMap();
            parametros.put("id", labelNo.getText());
            parametros.put("idpago", labelNo.getText());
            parametros.put("nit", txtNit.getText());
            parametros.put("nombre", labelNombreClie.getText());
            parametros.put("apellido", labelApellido.getText());
            parametros.put("numFactura", labelNo.getText());
            parametros.put("total", labelTotal.getText());
            
            JasperDesign dise = JRXmlLoader.load(archivo);
            JasperReport jr = JasperCompileManager.compileReport(dise);
            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, con);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(Venta2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void botonCargarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarClieActionPerformed
        if (txtNit.getText().length() > 0) {
            if (venta.existeRegistro("'" + txtNit.getText() + "'", "cliente", "nit")) {
                labelNombreClie.setText(venta.getDato("nit", "'" + txtNit.getText() + "'", "cliente", "nombre"));
                labelApellido.setText(venta.getDato("nit", "'" + txtNit.getText() + "'", "cliente", "apellido"));
                labelId.setText(venta.getDato("nit", "'" + txtNit.getText() + "'", "cliente", "id"));

                botonCargarClie.setEnabled(false);
                botonRemoverClie.setEnabled(true);
                txtNit.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "El cliente no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
                txtNit.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Llene el campo correspondiente", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_botonCargarClieActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        botonCargarClie.setEnabled(true);
        botonCargarPro.setEnabled(true);
        botonGuardar.setEnabled(true);
        botonCancelar.setEnabled(true);
        botonNuevo.setEnabled(false);
        txtNit.setEnabled(true);
        txtIDproducto.setEnabled(true);
        conexion.conexionMySQL.EjecutarInstruccion("START TRANSACTION");
        escribir.Escribirtxt("--INICIO TRANSACCION--", obtenerfecha());
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonRemoverClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoverClieActionPerformed
        limpiarModuloCliente();
        txtNit.setEnabled(true);
        botonCargarClie.setEnabled(true);

    }//GEN-LAST:event_botonRemoverClieActionPerformed

    private void botonCargarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarProActionPerformed
        if (txtIDproducto.getText().length() > 0) {
            if (venta.esEntero(txtIDproducto.getText())) {
                if (venta.existeRegistro(txtIDproducto.getText(), "producto", "id")) {
                    labelNombrePro.setText(venta.getDato("id", txtIDproducto.getText(), "producto", "nombre"));
                    labelPrecio.setText(venta.getDato("id", txtIDproducto.getText(), "producto", "precio"));
                    txtAreaDescripcion.setText(venta.getDato("id", txtIDproducto.getText(), "producto", "descripcion"));

                    txtIDproducto.setEnabled(false);
                    botonCargarPro.setEnabled(false);
                    botonRemoverPro.setEnabled(true);
                    botonAnadir.setEnabled(true);
                    txtCantidad.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "El producto no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    txtNit.setText("");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ingrese solo digitos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llene el campo correspondiente", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_botonCargarProActionPerformed

    private void botonRemoverProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoverProActionPerformed
        limpiarModuloProducto();
    }//GEN-LAST:event_botonRemoverProActionPerformed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        float total;
        if (txtCantidad.getText().equals("") == false) {
            if (venta.esEntero(txtCantidad.getText())) {
                total = Float.parseFloat(txtCantidad.getText()) * Float.parseFloat(labelPrecio.getText());
                labelSubTotal.setText(total + "");
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese solo valores enteros", "Advertencia", JOptionPane.WARNING_MESSAGE);
                txtCantidad.setText("");
                labelSubTotal.setText("");
            }
        } else {
            labelSubTotal.setText("");
        }
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese solo digitos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed
        int cantidad;
        if (txtCantidad.getText().length() > 0) {//ver que la caja de cantidad este llena 
            cantidad = Integer.parseInt(txtCantidad.getText());
            if (cantidad > 0) {//la cantidad debe de ser mayor a cero 
                if (!venta.existeEnTabla(txtIDproducto.getText(), tablaProducto, 0)) {//ver que el producto no este en la tabla 
                    if (comprabarExistenciasM(cantidad, txtIDproducto.getText())) {//ver que la existan materiales para hacer 
                        //anadir los datos a la tabla
                        String[] datos = new String[titulos.length];
                        datos[0] = txtIDproducto.getText();
                        datos[1] = labelNombrePro.getText();
                        datos[2] = labelPrecio.getText();
                        datos[3] = txtCantidad.getText();
                        datos[4] = labelSubTotal.getText();
                        venta.insertarEnTabla(datos, modelo);
                        //fin de insertar en tabla 

                        //restar lo que se necesita para el pedido al material 
                        restarCantidadMaterial(txtIDproducto.getText(), cantidad);
                        obtenerTotal(titulos.length - 1);
                        //fin 
                        limpiarModuloProducto();
                        botonQuitar.setEnabled(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "No hay materiales suficiente para realizar el pedido", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "La cantidad debe de ser mayor a cero", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad de material que necesita", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonAnadirActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        int fila = tablaProducto.getSelectedRow(), cantidad;
        if (fila >= 0) {

            cantidad = Integer.parseInt(String.valueOf(tablaProducto.getValueAt(fila, 3)));
            sumarCantidadMaterial(String.valueOf(tablaProducto.getValueAt(fila, 0)), cantidad);
            venta.quitarFila(fila, modelo);
            obtenerTotal(titulos.length - 1);
            if (tablaProducto.getRowCount() == 0) {
                botonQuitar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        conexion.conexionMySQL.EjecutarInstruccion("ROLLBACK");
        escribir.Escribirtxt("--TRANSACCION ABORTADA-- ", obtenerfecha());
        cancelar();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        conexion.conexionMySQL.EjecutarInstruccion("ROLLBACK");
        escribir.Escribirtxt("--TRANSACCION ABORTADA-- ", obtenerfecha());
        cancelar();
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        String abono, datos, parametros;
        if (labelId.getText().length() > 0 && tablaProducto.getRowCount() > 0) {
            abono = JOptionPane.showInputDialog("Ingrese el abono");
            if (abono != null) {
                if (venta.esFlotante(abono)) {
                    if (Float.parseFloat(abono) >= Float.parseFloat(labelTotal.getText()) / 2) {
                        //1) nueva factura
                        datos = "'" + venta.fecha() + "'," + labelTotal.getText() + "," + txtNit.getText() + ",'" + labelNo.getText() + "'," + labelId.getText();//dato para la factura
                        parametros = "fecha,total,nit,numFactura,cliente_id";
                        venta.nuevoRegistro(parametros, datos, "factura");
                        System.out.println("nueva factura");
                        conexion.conexionMySQL.EjecutarInstruccion("COMMIT");
                        fecha = new Date();
                        escribir.Escribirtxt("Se hizo INSERT en la tabla venta ", obtenerfecha());
                        DateFormat fechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                        String convertido = fechaHora.format(fecha);
                        escribir.Escribirtxt("--TRANSACCION FINALIZADA--", convertido);
                        //2) relacion producto factura con la tabla detalle_pro
                        relacionProductoFactura(venta.getUltimoId("id", "factura"));
                        System.out.println("relacion factura producto");

                        //3) hacer primer pago 
                        parametros = "abono,cliente_id,numPago,fecha";
                        datos = abono + "," + labelId.getText() + ",'" + venta.generarCodigo("numPago", "pago", "PD") + "','" + venta.fecha() + "'";
                        venta.nuevoRegistro(parametros, datos, "pago");
                        System.out.println("primer pago");

                        //4) relacion pago factura 
                        parametros = "factura_id,pago_id";
                        datos = venta.getUltimoId("id", "factura") + "," + venta.getUltimoId("id", "pago");
                        venta.nuevoRegistro(parametros, datos, "factura_has_pago");
                        System.out.println("primer pago relacionado con factura");

                        JOptionPane.showMessageDialog(null, "Venta completada", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                        generarFactura();
                        limpiarModuloCliente();
                        limpiarModuloProducto();
                        venta.limpiarTabla(modelo, tablaProducto);

                        botonNuevo.setEnabled(true);
                        txtIDproducto.setEnabled(false);
                        botonCargarPro.setEnabled(false);

                        botonGuardar.setEnabled(false);
                        botonCancelar.setEnabled(false);
                        botonQuitar.setEnabled(false);
                        labelTotal.setText("");

                        labelNo.setText(venta.generarCodigo("numFactura", "factura", "CD"));

                    } else {
                        JOptionPane.showMessageDialog(null, "El abono debe de ser mayor o igual al 50% del total", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Solo ingrese digitos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Llene los campos obligatorios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseEntered
        if (botonCerrar.isEnabled()) {
            botonCerrar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCerrarMouseEntered

    private void botonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseExited
        botonCerrar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCerrarMouseExited

    private void botonNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoMouseEntered
        if (botonNuevo.isEnabled()) {
            botonNuevo.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonNuevoMouseEntered

    private void botonNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoMouseExited
        botonNuevo.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonNuevoMouseExited

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
        if (botonGuardar.isEnabled()) {
            botonGuardar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited
        botonGuardar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonGuardarMouseExited

    private void botonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseEntered
        if (botonCancelar.isEnabled()) {
            botonCancelar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCancelarMouseEntered

    private void botonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseExited
        botonCancelar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCancelarMouseExited

    private void botonCargarClieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarClieMouseEntered
        if (botonCargarClie.isEnabled()) {
            botonCargarClie.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCargarClieMouseEntered

    private void botonCargarClieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarClieMouseExited
        botonCargarClie.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCargarClieMouseExited

    private void botonRemoverClieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverClieMouseEntered
        if (botonRemoverClie.isEnabled()) {
            botonRemoverClie.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonRemoverClieMouseEntered

    private void botonRemoverClieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverClieMouseExited
        botonRemoverClie.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonRemoverClieMouseExited

    private void botonCargarProMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarProMouseEntered
        if (botonCargarPro.isEnabled()) {
            botonCargarPro.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonCargarProMouseEntered

    private void botonCargarProMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarProMouseExited
        botonCargarPro.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonCargarProMouseExited

    private void botonRemoverProMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverProMouseEntered
        if (botonRemoverPro.isEnabled()) {
            botonRemoverPro.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonRemoverProMouseEntered

    private void botonRemoverProMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRemoverProMouseExited
        botonRemoverPro.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonRemoverProMouseExited

    private void botonAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMouseEntered
        if (botonAnadir.isEnabled()) {
            botonAnadir.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonAnadirMouseEntered

    private void botonAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMouseExited
        botonAnadir.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonAnadirMouseExited

    private void botonQuitarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonQuitarMouseEntered
        if (botonQuitar.isEnabled()) {
            botonQuitar.setBackground(new Color(255, 102, 51));
        }
    }//GEN-LAST:event_botonQuitarMouseEntered

    private void botonQuitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonQuitarMouseExited
        botonQuitar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonQuitarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCargarClie;
    private javax.swing.JButton botonCargarPro;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonRemoverClie;
    private javax.swing.JButton botonRemoverPro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNo;
    private javax.swing.JLabel labelNombreClie;
    private javax.swing.JLabel labelNombrePro;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIDproducto;
    private javax.swing.JTextField txtNit;
    // End of variables declaration//GEN-END:variables
}
